apiVersion: v1
kind: Secret
metadata:
    name: sense-credentials
    namespace: sense-exporter
stringData:
    SENSE_ACCOUNT_USERNAME_1: ENC[AES256_GCM,data:pY2MnfWJYHWIqsCz4QdgxNq5,iv:D959NqDMSv6eSXCU1ZVrNtuMXJwhfVykmf/hKfeeKIg=,tag:qWN799nRkyjqjaNaLWjxYQ==,type:str]
    SENSE_ACCOUNT_PASSWORD_1: ENC[AES256_GCM,data:Dk/+eO+D6AvOJ0Y=,iv:AkFNoEh0S44P/Gfyqr4UqD6Wv2J/kcxwkF5lhXUaK3s=,tag:KpJqWp7mF/IQ5jb7SB3Kug==,type:str]
sops:
    age:
        - recipient: age1qntcdwtxrfu92lhj2nzhlc3uqt8nxks5vw7rd23w2cj7c0qyuqqqmey085
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvRWNaNTY2L0NBaUQvSHlQ
            NkZxODUxUVJzcURDM0U3cXpTc3EvZ0dWSG1BCmF2VzlRTm9tQ2dBcXRYRzNiZWlD
            SGtCVHJ0SzZ0ZEd2VllPWTZVVHZZbjQKLS0tIDF4cW5SOFZFMHdxUUdzcXlmdWJG
            L1RWc3VjcmZacFloWnhkcTZDRXErd0kKrMQgc6giJLDTN3VtNMDrPvx/tlRkNjN3
            T7bFXROVL8f/G+7+PHVjAXKWLtDg8vH37HyosXaRmgrmAC8xPH+oxA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-02T00:50:53Z"
    mac: ENC[AES256_GCM,data:9FF54aj9iXyxHh6ReZMI2PbL2Cs+Qy53pAARAqpxbF/9mpUGEFJV+ITiXSDf91NxomnUrODm6u0CVuDkoqOSA6XF0rGRtiiULIxr34EkLqvSu44+bArvPKyBdEnXcs52JXKHwGyAnxA8W80ExG2A/SIyrzzdxvC0jTwJwX7yGMY=,iv:yw1vDF0QGaPm3BZxl6kj9wPAbyV69pWBSMfZ3NaxASA=,tag:r1LTlm0+AzfzSqXcVNTReQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
