apiVersion: ENC[AES256_GCM,data:V2s=,iv:6fEmHD3PGuS10ie+uJ7CQyaisFKIu0mwkLpb7E5VCRg=,tag:97/AGUfOwG/drkzDoaJ71Q==,type:str]
kind: ENC[AES256_GCM,data:Kz0uM/uF,iv:n+mYwGbXgAXOprN3LEucQWSeMHtx8zj1ufQ/cM5lwAI=,tag:wtG8KQbTxrA+LNfUb9aowA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:vU1TTeGhzkV3s2u97SzhdVg=,iv:uCNHCl4xSc2SAFeUdDvvKMYsA554VjWRu0NO+N3gPws=,tag:6Q93DuM3k0IQcPR2cPQlqQ==,type:str]
    namespace: ENC[AES256_GCM,data:s277C18+Zg08mDP/L0I=,iv:zjLoNeQfKCRvjXbYnlTH+WHuRLIzuSR8DUUJG+qs1tk=,tag:UsmH8+0bHXEYt4XUwuue7w==,type:str]
stringData:
    SENSE_ACCOUNT_USERNAME_1: ENC[AES256_GCM,data:H+yPLVGrDIHSABfwG3IUt3qc,iv:D4lICgbMGUOIQegFG8mM2VwmDZaH9InebfTodvXS5Lo=,tag:qYvuiF/nwLTbU7911mlUkw==,type:str]
    SENSE_ACCOUNT_PASSWORD_1: ENC[AES256_GCM,data:54NXo1rPGmAILDU=,iv:Oea2VP9LB/4pPif67Qwt3F9qyTGXXUNwwcQKOs1u/ds=,tag:4kEDXLtrcY1vb+mB2iJ+Vg==,type:str]
sops:
    age:
        - recipient: age1qntcdwtxrfu92lhj2nzhlc3uqt8nxks5vw7rd23w2cj7c0qyuqqqmey085
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhN1pUdjltUWxyY2xXdnJE
            cVRoaG9aZUxzaWpkcklrRVZhTGNCcjZWRUdJCmZJWG92cFVGWURDQm41bVA3b2V5
            dHpkSHZYVXBUZFNpbmlsWncxWjhqaFEKLS0tIDFGdEhJZGpsMjcySC9FZ1ZURTht
            MDBUeUhWeUN3ckFkUzg0dXdidjh1aFUKt+Q0mdM7tZqXT/gT7gb31+SFuDgzI3MW
            ATNC71Tt+KaoZHCx85sNRbu0gXZKfTNJlCpSQ1RbEC4EspDtXkOtAQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-02T00:27:35Z"
    mac: ENC[AES256_GCM,data:BzrtUC1dJMwWg7se9JIS2bvujVPJSVVSbZ+qqRri6lmV2eXkZJRSLRHFo9S6kUuZqqZF85vui007VBZOUXPTr2OdwpAp3FFfCRbLxOuUP4nTl6cFFu8SgXv1jrO5oSj/shMUaEoWL+JUGAk20dqV5qKt0Q5iMS6C6tR3MX9P/yA=,iv:U9Ar7RY3DglAuod/Wjr3vQx7pcKVXQIrbTzB8XDE4Bg=,tag:kUBQ2BUAnvVi8z7vzE+FYw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
