---
apiVersion: v1
kind: Service
metadata:
  name: sense-exporter
  namespace: sense-exporter
  labels:
    app: sense-exporter
spec:
  selector:
    app: sense-exporter
  ports:
    - name: metrics
      port: 9993
      targetPort: metrics
      protocol: TCP
