apiVersion: ENC[AES256_GCM,data:mF8=,iv:ieTPm2yWzdCnDEFcizMIiNv0XOB8Zd4c9hUtDR0KAIE=,tag:yOkNFeG2Exy4HwmG1FItPQ==,type:str]
kind: ENC[AES256_GCM,data:hRMoGL7P,iv:CY35vm56UZb9AzjuDYieCMoXdYIrssJM8/r0yHth47I=,tag:yYwybzOU5wfqfdDq3zcuSQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:DsmLPQYaDWZccCJQtBo1RsbMdO3JIQ==,iv:ZpwcDINlXZkzhYwFHlwiOQzfUBtaE2YLlXo9O/6u+YU=,tag:LowPyxEch9xcqkR+2GPxLA==,type:str]
    namespace: ENC[AES256_GCM,data:SDr5aTS++aYOXS5J,iv:e3pNUtshh/j5LRqP4e/77Ff70Pz0+3DsSA08WOzf/8k=,tag:UVOfaVU7ZVCZAe2+o/HO/A==,type:str]
stringData:
    password: ENC[AES256_GCM,data:BBQBqA0=,iv:g7dK1Ey8AWVJICYQ9LtyNYyHwSt+vp7Bz1J8gTascPA=,tag:QVwTfAAvDtpTNBpkMz8+Dg==,type:str]
sops:
    age:
        - recipient: age1qntcdwtxrfu92lhj2nzhlc3uqt8nxks5vw7rd23w2cj7c0qyuqqqmey085
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByaVNXYUV6TTc3N1BlTjhW
            TGgyMnhPOTFKMjhocFNiemtNREtLcXQ5TVN3CjNtRkRqckxqNU4yRjYwKyttZEtR
            M2dQVUxncVhpbG5ocThaVitaSDRQeWsKLS0tIEFVeW9jV3lUOU5lRjNOYWxrOTdk
            WFpxL2ZVaTlSVldmRFYwWHNGTlduNjQK/wcQCerjj1ztcoh/vIlow8Ovm/leEZNW
            mFbPSsu3W1bp7LCyHxjPGWfM0D2uh1dCK/Cn5W4FGYJF6whm7nBTWQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-23T18:53:47Z"
    mac: ENC[AES256_GCM,data:++iAlwPgtb7vB9yvINrgm4FSY0DFex+mg7HREVlefQUbb8saCVMNeyFKdvI6W70pSReAxVAMmAiyNtCZzYjtpRPOmKZfxvSX4JDwXtJz8V0XMWJtW4qz7s4IX46dXa/BWVLJAd3nEERKbXeZ+W9n9eYyj7G4z+oad5xSNWtgYHw=,iv:lZNq/rhKRjX7INDrXH2yerbA5E9YWvCSJEr6rHVfS7M=,tag:DIJ8nT21ih2dOQKgPZi9Qg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
