apiVersion: v1
kind: Secret
metadata:
    name: pihole-docker-password
    namespace: external-dns
stringData:
    password: ENC[AES256_GCM,data:1Hgo++k=,iv:XroeDpKemlslEBwVicHPa9F7M9WS7645jsHTmeVLO58=,tag:oENeI12Bb4bYI4TvDkY1ig==,type:str]
sops:
    age:
        - recipient: age1qntcdwtxrfu92lhj2nzhlc3uqt8nxks5vw7rd23w2cj7c0qyuqqqmey085
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3U3lpT3VzQ3RONGs5eSsw
            QVEwS2QzejQ4dW9nWXRpc2w0TzNqcU00RzFJCjFtMnFqY09zUmFpVFFCb1hubEw0
            aFdXb2tpNTBLR29FOFhoNjJjd3NZOVEKLS0tIEFkN2k3VmovdmdyY3hvaDVFd1M3
            elNjV3BJUUUwQzJaUEg3dVFHYVFaY1UKVpJ5PdIQ6hfVPcDPPQN+pqW4eJ9DZfnz
            TundtncIBk44rsy36p+zHhUnNjwEHhud/mltu+pA/dR6ToroViebBw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-02T01:03:04Z"
    mac: ENC[AES256_GCM,data:gfNrKpMOWSCSreeHIeecmcW4CqgsiT86P1ZLMvWXaYHPPqdQmEIdAw3iNB+rm4J6U4+qfTz/qAgDy5w4YNY3WxuqPU4GGUFuOiNe/Q3oSIlw9DMjqAmFnXoY8NsYedh8tcPVXnKMHDGk8UwgkY8YneSnG5T61GQL3osf2x+yzjM=,iv:LNQSSmvtV95pYNNHspMojhpyDUOR/LLr6ZjTxZoazzI=,tag:43iSHFkooxcmWiU71+rucw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
