apiVersion: ENC[AES256_GCM,data:omE=,iv:bkK7dpPaVQUaIuHx0QoO/WNcpcVDqNjMHf8PLh9m36g=,tag:TESZcpFbnjbVcZBZSZ56Bg==,type:str]
kind: ENC[AES256_GCM,data:NuFut6e2,iv:Wbx1PbFRdCx0rmmHwpek/mdVggtMrOCrgunrIXT/zqw=,tag:j1T0nAmQXOmO4Rsb6r8Nvg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:Gz++sROWpTymKtUJA4eBqfHt6w==,iv:dentQuQGqouSYsu3qzTo859HZMaFbyeiePzcCb+BH6E=,tag:iDJNs18hB5y+4w1xACBK5A==,type:str]
    namespace: ENC[AES256_GCM,data:o6Jj9MDCKWmx3Bdp,iv:pUObz3Rg6PdmH7rWBT6iTF86yTX99jiiMocwm9PZIfs=,tag:/J/CLVomwJeteNzA1p35gg==,type:str]
stringData:
    password: ENC[AES256_GCM,data:QOe2V5q3eK9lQF5EOw==,iv:rpQiB9KHckNpTw4TD1YUI0oe4ntRND3kUxf5X5JoRFc=,tag:+YVHbZSEPMUYlm6/XyfKLA==,type:str]
sops:
    age:
        - recipient: age1qntcdwtxrfu92lhj2nzhlc3uqt8nxks5vw7rd23w2cj7c0qyuqqqmey085
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1YS9tVXFScHNmQmo1NWo3
            ajMxMENyUzlsSGRnRno0WkpEckxBTVRId1RVCjRLWGhUWDJwSmxKMzhVSTFPaVpk
            TXNSeC9DU3MxKzkyaU9CcXl2MHRPUVUKLS0tIFNSZEVNYXpkWjZaMGFKbG11czc4
            cEtwK1FsRUIraUE2bmdmNTNwU2Y1blUKnO21hamtp4nahthV3IDTYWgbf7Sjboi/
            pgFVfP8Ju7Y2xHAjk4fRFd24gkxPD5eI03nWovgDo35CD8f1E/TaEg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-23T18:53:47Z"
    mac: ENC[AES256_GCM,data:tNLQdhFGd3bis+HeEINxUQGHKbGcetqN4fyK4w9TSawTgyEe7QEfm+Y7tIHQmcBj68DnDB+nrOyufvCNEwMIGHAaHTr26pmD1nNPxouX5+2KX0Qz9mD9g5fNFnQLOYZo3Xwz2+kwc+xbUR+bihOOQI0edKXOaKVzxYaKZtMEjkc=,iv:3kB4/xW/ZBw7IZR3L6QEUl0dEY7MSs0cGrX6sV9Ep4g=,tag:oHEoXm5ng53W4R4Pm3jwiA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
