apiVersion: ENC[AES256_GCM,data:hH8=,iv:8rW8cH+25IdIW7s9yiIebcIipBepbewo/xwZ8CLPjqQ=,tag:47OgMx3ahhb+nj6kxW9jCw==,type:str]
kind: ENC[AES256_GCM,data:anjU3eUa,iv:OxfJOQ45jbRdnifMqRgccBhPgozQxiS/XbWN00kK+u0=,tag:NVdYMVAKooN35TzDzOyYbQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:5nYCzDcaRcFTtMt817wRHI5ULw==,iv:5KXFhsdR9VnHtG6RBRYEg+uKM/e6hRVrmxIL8uygQ1w=,tag:UjhtjbyF6F9GZCdF+Lj74w==,type:str]
    namespace: ENC[AES256_GCM,data:bt+nUdPEfw==,iv:yS5azqLw5AWF0MCyj+8MZ81cD9t8nkmNSwtmouLDY+k=,tag:QC67jaF2V6s0t+NOzeEs7Q==,type:str]
stringData:
    wireguard-private-key: ENC[AES256_GCM,data:m68qkG8Ug32Qord4wHKFMbReORIgnW8xbSxDTn8qKjQUgdNLMVINLOxJ3h8t16uqCBy8nMM2VH/1dWCSMsybrw==,iv:t0fdwDCCZQO61f+QG/dgu45uXdklyYER5hpxzBzJLts=,tag:R+PHU7LkUFn+mrCiycP81A==,type:str]
sops:
    age:
        - recipient: age1qntcdwtxrfu92lhj2nzhlc3uqt8nxks5vw7rd23w2cj7c0qyuqqqmey085
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIbnMxV3ZqVGFMYTRVTnFa
            VmVtbzVZamU2VTNUdmFpZ1QvWHhQZlZ4bFdrCm92N1JVcndZeHN5WFpyVlh3TFE3
            MmVEbzV6bEZBNTdkejlYREdsWjNraFEKLS0tIFVIOUFSVjM0dFVrTCtMUnZTSmJk
            bXV0RG02L3ZHZHI3djBhaWhWM1VKTncKGscLDWdA4taAqo7aJBlPV15soL8GlCPw
            2/Ok/0vNz+Ti0Pi6sWcqpnqTGVU6YGWLcluJ8MB+WUXaV5xrnaHOIg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-24T00:27:38Z"
    mac: ENC[AES256_GCM,data:XjUUStH3R4rZz7oG+b3al9MsAuWdBWP3q1bgb+bccByMvddrDvO/lXfnbTSMWX+KYl/47Gh+RzZOQYoacbsqlMKGd7Qx56Bu5Z0PwX3VMSBpERI0Pt92Cs0SIBxfld/nRwVswTpUNsEug96bM13ZT/aluPg3fj34fvBJhi/dy0M=,iv:mhYdPtNbww0aBYe6xP89PhZe3M2Npva/p+dNA9iXMwI=,tag:aGcJzmXIQAwYSxBlDTvGVQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
