apiVersion: ENC[AES256_GCM,data:hH8=,iv:8rW8cH+25IdIW7s9yiIebcIipBepbewo/xwZ8CLPjqQ=,tag:47OgMx3ahhb+nj6kxW9jCw==,type:str]
kind: ENC[AES256_GCM,data:anjU3eUa,iv:OxfJOQ45jbRdnifMqRgccBhPgozQxiS/XbWN00kK+u0=,tag:NVdYMVAKooN35TzDzOyYbQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:5nYCzDcaRcFTtMt817wRHI5ULw==,iv:5KXFhsdR9VnHtG6RBRYEg+uKM/e6hRVrmxIL8uygQ1w=,tag:UjhtjbyF6F9GZCdF+Lj74w==,type:str]
    namespace: ENC[AES256_GCM,data:bt+nUdPEfw==,iv:yS5azqLw5AWF0MCyj+8MZ81cD9t8nkmNSwtmouLDY+k=,tag:QC67jaF2V6s0t+NOzeEs7Q==,type:str]
stringData:
    wireguard-private-key: ENC[AES256_GCM,data:GWMok12RiDbOoiAcp/1tDVSSfuHwp59pvbA5FbQFd7L8GrBHdrmSsFoAMc4=,iv:T5SNE4IW2vLsNPfAdsmD+3pLed2M/K0X3pJbB/5TxpQ=,tag:2vHRXEILsWBl/8r5NFcbog==,type:str]
sops:
    age:
        - recipient: age1qntcdwtxrfu92lhj2nzhlc3uqt8nxks5vw7rd23w2cj7c0qyuqqqmey085
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIbnMxV3ZqVGFMYTRVTnFa
            VmVtbzVZamU2VTNUdmFpZ1QvWHhQZlZ4bFdrCm92N1JVcndZeHN5WFpyVlh3TFE3
            MmVEbzV6bEZBNTdkejlYREdsWjNraFEKLS0tIFVIOUFSVjM0dFVrTCtMUnZTSmJk
            bXV0RG02L3ZHZHI3djBhaWhWM1VKTncKGscLDWdA4taAqo7aJBlPV15soL8GlCPw
            2/Ok/0vNz+Ti0Pi6sWcqpnqTGVU6YGWLcluJ8MB+WUXaV5xrnaHOIg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-24T00:44:06Z"
    mac: ENC[AES256_GCM,data:30hYp6agvQMrOTKVy0TZkM27AhIC5RFfhmntnTcNMb0ZHlFiTrPP1zUMuB7H6dFlCKBr3WwcXH6Vzpy1GzXw8hbyZ/NcDwzF/rpjlvWO1UN1m1gcXyAhQqZ8NkGGGSezsvGJhdMpJtmIVQTF0NxVPqLyGvusD7j87mgxJIZbkWk=,iv:fuM0FCzprqKsCXbzeQKOJJzJtI/MAt42yZO9HxeWdWo=,tag:aHRKZEZFJZfp8vRluTueGg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
