apiVersion: ENC[AES256_GCM,data:/sg=,iv:VNfpodPEzm76QDJaty0ibu7pVg/BeCSojgvjTmhvV7A=,tag:JCjVdF/juq5WnoP0Re312Q==,type:str]
kind: ENC[AES256_GCM,data:PmU7aW6q,iv:/QNqtlvYeYDXQmPJXJ/pPvJ8E8em+OGDrRCcpM/BiGk=,tag:dfDwlktRVMNqIUnCu2yM/A==,type:str]
metadata:
    name: ENC[AES256_GCM,data:0pUr9CEXAY+LhDirXON1J/EkSQ==,iv:Hu88X+6y/dAvm9UlRQtlngn1wIfpXVoI5JryZ3YMDNg=,tag:hIdcAFjb7QFxtv1VzrLABg==,type:str]
    namespace: ENC[AES256_GCM,data:RCRIi0OnIA==,iv:B+NAtSTiLd7QPgi91d9SkU59bsgJ0OjPQWr93Wup9Dw=,tag:STwVj/CFpfMVJG5F6f+8sA==,type:str]
stringData:
    wireguard-private-key: ENC[AES256_GCM,data:VsYBimoQdDZK3StiHx3YS0UJ7xZhAi1v6M7iLCzyAtuaTb9VxMOS/TlpLUTrFw==,iv:AK3QXiY/WxduY9oU1CaA6lYzuRuY+yJtq0ih9A0BRJY=,tag:JvxAuW68L5JVZbmW0/jVPA==,type:str]
sops:
    age:
        - recipient: age1qntcdwtxrfu92lhj2nzhlc3uqt8nxks5vw7rd23w2cj7c0qyuqqqmey085
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBYjRXWVdleHJ4L3dnK1hi
            QnhGdXdsZzJMK2VCWUUxeWphN0wySFhPVVFjCjFMVTc1aThjL0QxUmN4aTdTdGJR
            b215L1lZVFhWcGxUWjhQQ2Nqek5talUKLS0tIE9heGp5RFVnaFd3dDJmbDB1NG8v
            UFE0SEhWOG1YdW8vUlFQaFJWMjg2V3cKwK4fxVNJtvamx8C57i561PXFQXQ/PI7l
            E7TBPXdOZh1DuVf8LLRmdLJ39LucnR/7CNsO/6/r/Sa6sIoLeOmxPA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-23T23:22:29Z"
    mac: ENC[AES256_GCM,data:yfKB7vLPj/PNbI2camBbCfwYzpQkwcN0c/p0xxBb9xraAYD1WJjggRCzuI61SrIT2fRG1Si+Tg6XdeErPNg3wAU4uUg2Y3Lm8siLFU6hLiLHClf97EhqOBydZcaoRBgfm9g8Pyso/hw4FLRTmrdeaEjhNbHIkR/eqyhRrg9Gf0s=,iv:ciRfeEY4tZ81ap9W5M2ZU9NDQwDp29ImjnOM4mRjLU8=,tag:3RjGxF7agc205qylnDeD+A==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
