apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sabnzbd-config
  namespace: sabnzbd
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sabnzbd-downloads
  namespace: sabnzbd
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 200Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gluetun-config
  namespace: sabnzbd
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sabnzbd-media
spec:
  capacity:
    storage: 10Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: smb-media
  mountOptions:
    - vers=3.0
    - dir_mode=0777
    - file_mode=0777
    - uid=1027
    - gid=100
    - noperm
    - cache=strict
    - noserverino
  csi:
    driver: smb.csi.k8s.io
    readOnly: false
    volumeHandle: sabnzbd-media-volume
    volumeAttributes:
      source: "//192.168.1.20/data"
    nodeStageSecretRef:
      name: smbcreds
      namespace: kube-system
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sabnzbd-media
  namespace: sabnzbd
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: smb-media
  volumeName: sabnzbd-media
  resources:
    requests:
      storage: 10Ti
