apiVersion: v1
kind: Secret
metadata:
    name: sabnzbd-apikey
    namespace: sabnzbd
stringData:
    api-key: ENC[AES256_GCM,data:EO8Y706/e4tHzu3vJ2ReEU0Kk6y9nvqj6j8FnoF6fxA=,iv:SHJ05sWeKJ38VDBJnEb/LdAITcyGtB+tYhve/3qrQME=,tag:aNwNWlszJNgSLraRCkrDng==,type:str]
sops:
    age:
        - recipient: age1qntcdwtxrfu92lhj2nzhlc3uqt8nxks5vw7rd23w2cj7c0qyuqqqmey085
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrcDd0YUM2VnlGL2RKZ2xP
            UzEyTjFteU1qd25xaWJIaHBscHRURUUxblNBCnljbmR4RmdRTHJ6UllHQkd2K0tp
            b0JPWXE5clA0TGhNUDZLYkkrNzEzZmsKLS0tIFFzejdqdFE1cjQyaVVobXFxR2VW
            U3BoRHBxUjh3NG9BUms2Q0tBTGRyZnMKaKe/S+pW8ND70CkXhPE5rfqdxhe2flt9
            R+NHIS9OwP9MZlyVpAe5b/CrgIdh/+h+IFs/duO5G3gxvAcP1lNDzA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-02T01:03:04Z"
    mac: ENC[AES256_GCM,data:AH0BzGJn8qEFPAJw4rzNFQN3MJ+vsjb+f8MvlDkD4V6+ARuVJGpm1xBC/pxdCXIGZmo5speqDeuvuh6vLRlp077danKHuDZThiYM9GPZGL+n4RewfKh12fQR1+o9iygvUn7vYVvuP/97fDf1VdfxeizCaciBELUqjpiReaFbb+o=,iv:ANRGuejp/9kug639Qpa2gat/lPMTo8wiGVbmDnCzArw=,tag:Dfs02m0qyKyLPAjyV8rldQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
