apiVersion: ENC[AES256_GCM,data:cG8=,iv:w28TwnFLXhtPHzrFTTk5vv3HOAkqxwEyLW/u7SS0Ylk=,tag:Ta8T4Nja5jytjyzxKhInlg==,type:str]
kind: ENC[AES256_GCM,data:Zs9kjH54,iv:kyO+QDuiah05LkGpwLdfM0fRBldmPoXIpKcgBWQ9gd4=,tag:NZipi8eYLM00uduT2Bw3Lg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:Y+LkDfcYcMKhStysVrw=,iv:OB+2Pe7iOLvWSshsmv9CSgGaDifCFSOd2/EFB6S6mGA=,tag:a+T05GGwTAtCL8kuO5MDww==,type:str]
    namespace: ENC[AES256_GCM,data:YjEFvPj3jA==,iv:bYgTBD+DCGdwgmtgSRH8Xm9XzJ0yPOw6qjOSRPrXxxo=,tag:CNlwBouJ4EQj68jWr1q70g==,type:str]
stringData:
    api-key: ENC[AES256_GCM,data:aeVQ9wapFQHHNv6f6efdgjvOOK49ZV+tzlqo75XIkwA=,iv:JeLKJ990YOf0ArNTP5u/7br76AjAzvuF+hZVJELmAaM=,tag:fDxx2i60df1Apquy1kqVJw==,type:str]
sops:
    age:
        - recipient: age1qntcdwtxrfu92lhj2nzhlc3uqt8nxks5vw7rd23w2cj7c0qyuqqqmey085
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwL1BwVHlQTFUvY1NrVkMz
            ZjZjVmE3Q0EvRC9PbldLU1lTZCtXU01oWEVzCnI4Z1NCWFg0d1lYQWcxWEp0amEy
            ZC9YSm41ZWZKTjhmM3dGNXlGWjM4elEKLS0tIFpZWUJESExINFlva0JsUEwrYWdw
            ZzdGY2s4UWZRMGN5NWh6YWJqcGFGaDQK/lyLVbCqje5pRSncPudaPfBHikuVwbcl
            0HMdywSEVKj2xTxE+kIDt/UOx1Sd9TBdS9PEsRpmlJbK9xkLYpBipw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-25T00:10:40Z"
    mac: ENC[AES256_GCM,data:1yqYbt0vuoRScWlTAEOHwGJEgqcxVOL6pRmjD5BM7BQy3gmdhjdvirrroasOlDP+e1QfXhGgo7v3WYPkY+msCH4EVxpl3WCSoMdi9ysznej8MdnLoDyKeDzuD9NzO2KU+Gl57VleUaA7FTY4nRaX4V8Qsql5E85IM0j8TaCEhhc=,iv:R4ffpVK4xncnq8xfy0DBTd2K3LGm2i84PjtxLzZajUk=,tag:iVkcuIVm5pe0DxMNMCxN1A==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
