apiVersion: v1
kind: Secret
metadata:
    name: sabnzbd-apikey
    namespace: sabnzbd
stringData:
    api-key: ENC[AES256_GCM,data:UccNjb58yAkW7GxBkxxxRySR8gifNSNWXfGyYNB/f+E=,iv:a3ZcEEOQISLpkTkGJ9yjlS9sXJ9/9TlLIS3Uur1ckQI=,tag:8Jf8j0R4npKhc7ILuIitUg==,type:str]
sops:
    age:
        - recipient: age1qntcdwtxrfu92lhj2nzhlc3uqt8nxks5vw7rd23w2cj7c0qyuqqqmey085
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrcDd0YUM2VnlGL2RKZ2xP
            UzEyTjFteU1qd25xaWJIaHBscHRURUUxblNBCnljbmR4RmdRTHJ6UllHQkd2K0tp
            b0JPWXE5clA0TGhNUDZLYkkrNzEzZmsKLS0tIFFzejdqdFE1cjQyaVVobXFxR2VW
            U3BoRHBxUjh3NG9BUms2Q0tBTGRyZnMKaKe/S+pW8ND70CkXhPE5rfqdxhe2flt9
            R+NHIS9OwP9MZlyVpAe5b/CrgIdh/+h+IFs/duO5G3gxvAcP1lNDzA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-21T22:58:10Z"
    mac: ENC[AES256_GCM,data:1E3kDAS9GkRB/Fl0Ozt+zizrPxieOD6Qrua9R+fcqYWoBoahp3U+Ucq1LhujJozwl4GvIThxOujjegYVhGOT3C714XlLyR93Qkv+i2+p0pl3r3EKxoAgfJielPm7wbzTNyk6K2yA97DDsFIfZLdl5UGNciFK8rCkwYNUgX5SB9Q=,iv:Ibswx+Xe7zWYwWuRWKKD7XdBAVMzR0nGAIpiw88k6Ms=,tag:9HEJsvcfNQ3ywF9yvwT4WA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
