---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tdarr-media
  namespace: tdarr
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: synology-media-rw
  resources:
    requests:
      storage: 28Ti
