version: "3.8"

services: 
  portainer:
    image: portainer/agent:2.39.2
    container_name: portainer
    environment:
      - TZ=America/New_York
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /volume1/docker/volumes:/var/lib/docker/volumes
    ports:
      - 9001:9001
    network_mode: homelab_bridge_network
    restart: unless-stopped
