apiVersion: v1
kind: Secret
metadata:
    name: headlamp-oidc-secret
    namespace: headlamp
stringData:
    OIDC_CLIENT_ID: ENC[AES256_GCM,data:S5Lkkt8ufEA=,iv:fvgtSj5SwjTngr07EGiPLoezOdYT5b7DP/FZuQB/72w=,tag:nYvWoq5CWESUceOoCqAZww==,type:str]
    OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:inzBRWOmm1Rc+dRYDwb8mZ3xUGdigs9WrzdeupRsuHo=,iv:/DovsuU0YdgZ+yUa2pRs4za2yAteFBaioTHua0s7Rbg=,tag:sb3Rw76Le+nO6Py431vpAw==,type:str]
    OIDC_ISSUER_URL: ENC[AES256_GCM,data:8qO5V6Kujt/LeI078fJFxNqvQ1Lsd0laGVw3OR5cqw1sEMqEUsGSyhnPHByajbYe+prPnSYiwA==,iv:2rJiiI+mkFbKIGRmWLP38QSRQ6Ra3RUXtrxD+DA3ftQ=,tag:2DVRUoK+4OMKCwm51Clctg==,type:str]
    OIDC_SCOPES: ENC[AES256_GCM,data:AQhgmiMGVbjq8ELXHyEM41wMTW+FsctkXYHMV8Emjo7cbA8=,iv:k0MoR3nvLw3X5FoT/MYPFVP8u0pX69DsLLgWo2SmoJI=,tag:GIcjI3s0njJLzAIYNiQV3Q==,type:str]
sops:
    age:
        - recipient: age1qntcdwtxrfu92lhj2nzhlc3uqt8nxks5vw7rd23w2cj7c0qyuqqqmey085
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIY2dabGQvOVVuT3VkV29E
            a3BtdFl3YmVWckltUmw4emtaSDBHMGxMZTJjCi9yVzk4Vm1CN2FSc2VJVDN1Y3pN
            UjRranZqRkhkZnYxSnE5MVQ5RlRoeEUKLS0tIE5mQ2lMSldEQnR4cjRJdHJoSlkr
            eEw1c1Zha0s3T3JNRUhXNXlIRXlWKzgKnfM0seFu/wCQhq7ykesLiWB1jIUaX8AN
            rQPV9ZqiJMNJqt6mULzHMhjGHr2pCYuh7htUiBDQgivjn5VHwmktwg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-02T01:03:04Z"
    mac: ENC[AES256_GCM,data:6WwuNa7glvrbN0PmhvgfLtD0NO//38xRvWpp1JrvbFw0kisbNjl8BAxtpTo6hIcrY8w00Mr0mVWZU/vuHghlC+XoPrbFPPu5wz73mO+xHVrKNoSpDGnQdixykdryVnK3e6nh1b6aupT0phTJ3Lpo0rORhLCzQrDr9d1OmMFI+W8=,iv:DbEklEsNfrhpCrE84mC6P20tzHW6aQFQq//9nOfjDJI=,tag:7V/+kLf65Cp8wL0fCT050w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
