apiVersion: ENC[AES256_GCM,data:VPs=,iv:hOINFxUPSHcVggYbYIW8Mgqm5EeACgt6shHCVFc55B4=,tag:iZwzvWFug2VHvkmz6EsjzA==,type:str]
kind: ENC[AES256_GCM,data:J6AmzNj+,iv:kJufyKWN7V7FuqTZlNl/dLbrh77QogAmP7b3ql80Zzw=,tag:SSVZDeOVMfY+Web+7mK0RQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:zpuHAWENdlpzTsY5cgqanEHVuPM=,iv:iRQvv/V/9B/u0rFlF4+kZKRFUtz47NkvfYmSvsCXNcs=,tag:CItsm3q7Ejf6g7UHuDRLEg==,type:str]
    namespace: ENC[AES256_GCM,data:K4Iojxcufng=,iv:zEMhPprZpnnIiASTWfMB8Z3zk2+tZq45Rxjo8uuUDmg=,tag:VFglIs6LHGCOQze5cuKVXw==,type:str]
stringData:
    OIDC_CLIENT_ID: ENC[AES256_GCM,data:KzI+9gMQxWw=,iv:ddmMw6cYFAP3I1Vt9WV6yWbC1yT9cq4tLg+gfftqWOs=,tag:JGytTm5xFIocB8MvRL6YvA==,type:str]
    OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:pj4YXARSIUcqnlreY4oWtMp7TnxszlPNmPfDiLtt5xg=,iv:Vb/TsaIjWoKBnzel+Dh+IiChyu5+cerk9m9li6GpMlU=,tag:52dLUh+o/AkCaLr0/sNoqA==,type:str]
    OIDC_ISSUER_URL: ENC[AES256_GCM,data:sVi7YbRKLMNd3z0Mz3hBLgWxD4efsar6QELg0bXhGeE/Si7tSfr4dxr9KetCvKMpuHs02iRYkw==,iv:WxLGP4epf5OIdNGVWNBXruSk+0qj2w5WgxgY/gf3sj4=,tag:VHireAGpUsXvykceEU7bqw==,type:str]
    OIDC_SCOPES: ENC[AES256_GCM,data:ikzw22wXsepDdmRhyouX9Cb2XRIhUQYVHa9cE4c+pVUsCjg=,iv:iTeuLa+R3QHDLVoxY+1GwzKJ0iDvuLdzo8t2Hx5oFPY=,tag:O9DCU72UocuRxX1uNlMTlA==,type:str]
sops:
    age:
        - recipient: age1qntcdwtxrfu92lhj2nzhlc3uqt8nxks5vw7rd23w2cj7c0qyuqqqmey085
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxQ1hUTDZhdWQ2NzhpVTlM
            dllqd0w0ZFdvcXU0T0tnbVNlRlBmYzQ0SEYwCk1uRmRKTitnYWxwa3BwZGV0aFpa
            WjVRZTI4OVhDT2d3NlMyYkxwVG5NVG8KLS0tICtIeWhlRmFCM0c0NjBIYnVSZWla
            TS9JOWx1VFhJWHptZHNjdVdqd1AyQncK8MSuitmQCPbqm+27a8Tc9vB5z9x4H09Z
            A2WBWbistIQk7FwwucyNow9mLnPXhQQMMztnhXefu2z5Tkj7ACxFIA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-10T21:44:14Z"
    mac: ENC[AES256_GCM,data:Teb8ZxBbJsNysgXTC6LWKcMUGIG0odocPhkAA2czVLqHGdPeiqDhGKUIFDSRs0v0G3FlsT3wVjTZ7GlTOmewP6mDckjRBJm5XGKll8gu4TrgzbA6NsIOAgf/TWagAP/VXVGmvAUtxjx1kVcd3wKR5mX9F9rjyyIavvMEbR2G2jA=,iv:Xf1+uXF5R5Pe2rRDdVVsuNHk5K7PJMygVOdCQ6uXTHI=,tag:llod2hm9z4116hxd3Bg2Uw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
