apiVersion: ENC[AES256_GCM,data:aYg=,iv:ZPJDWiLWWexAHtT4oJrN9Ys8zFb6V95Qz8oB6EK3GLg=,tag:EvQQMruJciNN4J0jgSJbZg==,type:str]
kind: ENC[AES256_GCM,data:kEWPy2p0,iv:31XFm86VSHlLkixBrTe7KN8pdF4RqP+YwKgy+yX+7CQ=,tag:UBnQLXV+QQ1vgGK767L7Zw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:ohA89kVcZt+a5aMV9BxOD55Jn1o=,iv:vzZoaitOVmIMqFUfFPwTCUPPL6UxvLM/MtHCSSVzI0Y=,tag:5lFXR8K07/Tzmkg+RHn0fQ==,type:str]
    namespace: ENC[AES256_GCM,data:7F96Ii1D2qY=,iv:gVATdgMjg/PQfbWTH/5sid1m2Zs4NCpRGnyRCvPXVeQ=,tag:hQQuX3Ow4eRq7bvqk/a4sQ==,type:str]
stringData:
    HEADLAMP_CONFIG_OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:XfxjIpaTK4gn/3n8NWhJXp09wR7j8YH2/LuG1pNuUgE=,iv:wd4nz9gz+LUhKLC7nhDe4fp7VtiqgCaf5PSjh+Zy3AM=,tag:V+VaCHY43yOPO5XxckCGaw==,type:str]
sops:
    age:
        - recipient: age1qntcdwtxrfu92lhj2nzhlc3uqt8nxks5vw7rd23w2cj7c0qyuqqqmey085
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlS1hSaUV0MjFlV1hPb0lD
            cmxidmM2VklzM2RPZGlvdnZjNzFjMmZCZGgwCmQzTUIzLzlmd1hUNGdvVGdvNXdO
            SFlONSs1S2QzOVNWRGZ1bW0zTDlhLzQKLS0tIFNsUGZXcE5ncWxRY0Z4dWtXVXZD
            VGtncEtuYXA3YTRRNU1hL2NnWVZjR2MKV2dTqu69K3BkIfq0yNSA5uJN+B/IjQl+
            YiRQSdR4RWZCni18ICfO97fbhizsjIqzX3e2s5rIl55zDAmdx30Fmg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-09T19:37:09Z"
    mac: ENC[AES256_GCM,data:WmGVdsfzj5nd4/RXLc1olNPxBFRFoJg5lNxCytS//mTzYbHxcNUUS4H7A7MiAuojGhsVaDF2rgaA8uv6vsQsLEKQ0XHmK4nxhGDJftBAvY5yLBorsweUqgTaJwLWVxPaq3B6bpoiD2ysZBYFgcXD3daM1btB9k1bHxUo7migP3g=,iv:GtFxTy26XB00ORKK/YcOAKY7MiSPYraTU6EOsgui5lE=,tag:6LIDHrV2anD9lv/8X8vtWw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
