---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: headlamp
  namespace: headlamp
spec:
  interval: 1h
  timeout: 5m
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  chart:
    spec:
      chart: headlamp
      version: "0.41.0"
      sourceRef:
        kind: HelmRepository
        name: headlamp
        namespace: flux-system
      interval: 12h
  values:
    service:
      type: ClusterIP
      port: 80
    ingress:
      enabled: true
      ingressClassName: traefik
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
      hosts:
        - host: headlamp.homelab.properties
          paths:
            - path: /
              type: Prefix
      tls:
        - secretName: headlamp-tls
          hosts:
            - headlamp.homelab.properties
    config:
      inCluster: true
      pluginsDir: /build/plugins
      oidc:
        clientID: headlamp
        issuerURL: https://auth.homelab.properties/application/o/headlamp/
        scopes: openid email profile
        externalSecret:
          enabled: true
          name: headlamp-oidc-secret
    clusterRoleBinding:
      clusterRoleName: cluster-admin
    initContainers:
      - name: headlamp-plugins
        image: ghcr.io/headlamp-k8s/headlamp-plugin-flux:v0.6.0
        imagePullPolicy: Always
        command:
          - /bin/sh
          - -c
          - mkdir -p /build/plugins && cp -r /plugins/* /build/plugins/ && chown -R 100:101 /build
        securityContext:
          runAsNonRoot: false
          privileged: false
          runAsUser: 0
          runAsGroup: 0
        volumeMounts:
          - mountPath: /build/plugins
            name: headlamp-plugins
      - name: headlamp-plugins-cert-manager
        image: ghcr.io/headlamp-k8s/headlamp-plugin-cert-manager:v0.1.0
        imagePullPolicy: Always
        command:
          - /bin/sh
          - -c
          - mkdir -p /build/plugins && cp -r /plugins/* /build/plugins/ && chown -R 100:101 /build
        securityContext:
          runAsNonRoot: false
          privileged: false
          runAsUser: 0
          runAsGroup: 0
        volumeMounts:
          - mountPath: /build/plugins
            name: headlamp-plugins
    persistentVolumeClaim:
      accessModes:
        - ReadWriteOnce
      enabled: true
      size: 1Gi
    volumeMounts:
      - mountPath: /build/plugins
        name: headlamp-plugins
    volumes:
      - name: headlamp-plugins
        persistentVolumeClaim:
          claimName: headlamp
