apiVersion: v1
kind: Secret
metadata:
    name: unpoller-credentials
    namespace: unpoller
stringData:
    UP_UNIFI_DEFAULT_USER: ENC[AES256_GCM,data:Y0d9pTmXMo1ZVXfv,iv:/++pmhkx677qzE6elgXiv6Fy1MiAKY65yXv91kr8mrw=,tag:24gybbE6PpxUGCIYwXwUcQ==,type:str]
    UP_UNIFI_DEFAULT_PASS: ENC[AES256_GCM,data:l+vIhS9RHq+RHP+b,iv:0qiyJ1FBQM01hXtlYuGRDhPBSkPINqZMvkQ/REy03CI=,tag:L7fH0ry/tbL59W7T/uSILg==,type:str]
sops:
    age:
        - recipient: age1qntcdwtxrfu92lhj2nzhlc3uqt8nxks5vw7rd23w2cj7c0qyuqqqmey085
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVOHhOcmRkVkd1Z210Zk05
            Qlkwc2syc3ozSXQvZ0c3SHpsSUcvaWo0RkFNClNaV3VhajEyOVFUb3pVTjZjdllk
            d3E0ZEhhMmc2Snp1NkdSS3YrcGpjN0kKLS0tIElvWU81bjU1b1VnTDFYYW9BR0pQ
            OGd3cThoTFQ2L1ZieGo4emlNL1F6L0UKChggvNKx2JRD4Q8MYjYa8mf/sxVwR3Xg
            bhrFstzoKGMbL+m0p05ow0A0x+STMrG0rQX3wwLEnh+kb21yb5VhhQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-03T21:45:32Z"
    mac: ENC[AES256_GCM,data:/wcw+uXxCBSoGhz3MRQtJW7lv7NSH1FehDMPHIyQcl8ppfBnO4LJPB2vQOhl9/rEVNzSzCNl5XFM3AwoBfzVNmJW3ftZTiRIm7LATYPQQykJxGEh9A8BTn5ngZlnYdSZIcoUXB2p36WVsjimMbpY8BS7mQISVTM1S8OEXDYlHek=,iv:U7yI7gK9vuhCF0+yHHkc5sS4h31mJ9RwGOU26xoPRmg=,tag:3heMwBmjehJwXEkswuWa+A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
