apiVersion: v1
kind: Secret
metadata:
    name: unpoller-credentials
    namespace: unpoller
stringData:
    UP_UNIFI_DEFAULT_USER: ENC[AES256_GCM,data:fFniFHVx4ReOg+JHpeUwf8S5NpMXtxWBJQ==,iv:g0tBl5M7waxkxtkzjzuP6hNPMzyGTBAxhxQS2rvmImA=,tag:EvVKJNpW1xf1f+giG/tnUg==,type:str]
    UP_UNIFI_DEFAULT_PASS: ENC[AES256_GCM,data:ZGgKRZe18Ph9KsbfstN7e6a8alw667RONw==,iv:9l89W8blPHQRrVOMdzFKzRaGJLkrrfBQMiFcaNVHwWc=,tag:UrIO/eQUpjnJMBREdHtqHA==,type:str]
sops:
    age:
        - recipient: age1qntcdwtxrfu92lhj2nzhlc3uqt8nxks5vw7rd23w2cj7c0qyuqqqmey085
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVOHhOcmRkVkd1Z210Zk05
            Qlkwc2syc3ozSXQvZ0c3SHpsSUcvaWo0RkFNClNaV3VhajEyOVFUb3pVTjZjdllk
            d3E0ZEhhMmc2Snp1NkdSS3YrcGpjN0kKLS0tIElvWU81bjU1b1VnTDFYYW9BR0pQ
            OGd3cThoTFQ2L1ZieGo4emlNL1F6L0UKChggvNKx2JRD4Q8MYjYa8mf/sxVwR3Xg
            bhrFstzoKGMbL+m0p05ow0A0x+STMrG0rQX3wwLEnh+kb21yb5VhhQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-03T21:28:21Z"
    mac: ENC[AES256_GCM,data:JmXheffP52rHN3vKmuG4x8wNyDJQ17VljM8hBtcW3Rue8kLVDesbPa3s9FXVaA/HXgfFZHMSDHuhDrOJ/30zyM0DAYE8rmAdAOoKp1aEoLcg4rZxbL9FN5UE+M6EPndTZe52CUE9YaeRy7XkFemx0LpUQatNV/1AOZeBY76HXM4=,iv:o9mr3YSrNW+wmwuK5Mx8D5plHVAtfn9BRVPrmCUQ1RU=,tag:58lHHPBbt3DXHL3EZwQLUA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
