---
# k3s/infrastructure/configs/kopiur-policies/snapshotschedule-sabnzbd-gluetun.yaml
apiVersion: kopiur.home-operations.com/v1alpha1
kind: SnapshotSchedule
metadata:
  name: sabnzbd-gluetun-scheduled
  namespace: sabnzbd
spec:
  policyRef:
    name: sabnzbd-gluetun
  schedule:
    cron: "45 * * * *"
    runOnCreate: false
