---
# k3s/infrastructure/configs/kopiur-policies/snapshotschedule-tdarr-server-data.yaml
apiVersion: kopiur.home-operations.com/v1alpha1
kind: SnapshotSchedule
metadata:
  name: tdarr-server-data-scheduled
  namespace: tdarr
spec:
  policyRef:
    name: tdarr-server-data
  schedule:
    cron: "H * * * *"
    runOnCreate: false