---
# k3s/infrastructure/configs/kopiur-policies/snapshotschedule-qbittorrent-gluetun.yaml
apiVersion: kopiur.home-operations.com/v1alpha1
kind: SnapshotSchedule
metadata:
  name: qbittorrent-gluetun-scheduled
  namespace: qbittorrent
spec:
  policyRef:
    name: qbittorrent-gluetun
  schedule:
    cron: "34 * * * *"
    runOnCreate: false
