---
# k3s/infrastructure/configs/kopiur-policies/snapshotschedule-sonarr.yaml
apiVersion: kopiur.home-operations.com/v1alpha1
kind: SnapshotSchedule
metadata:
  name: sonarr-scheduled
  namespace: media
spec:
  policyRef:
    name: sonarr
  schedule:
    cron: "49 * * * *"
    runOnCreate: false
