---
# k3s/infrastructure/configs/kopiur-policies/snapshotschedule-grafana.yaml
apiVersion: kopiur.home-operations.com/v1alpha1
kind: SnapshotSchedule
metadata:
  name: grafana-scheduled
  namespace: monitoring
spec:
  policyRef:
    name: grafana
  schedule:
    cron: "H * * * *"
    runOnCreate: false
