---
# k3s/infrastructure/configs/kopiur-policies/snapshotschedule-authentik.yaml
apiVersion: kopiur.home-operations.com/v1alpha1
kind: SnapshotSchedule
metadata:
  name: authentik-scheduled
  namespace: authentik
spec:
  policyRef:
    name: authentik
  schedule:
    cron: "4 * * * *"
    runOnCreate: false
