version: "3.8"

services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    hostname: prometheus
    ports:
      - 9090:9090
    environment:
      - TZ=America/New_York
    user: 1027:100
    volumes:
      - /volume1/docker/homelab/prometheus/etc:/etc/prometheus
      - /volume1/data/prometheus:/prometheus
    networks:
      default:
        ipv4_address: 192.168.1.3
      br:
        ipv4_address: 172.20.1.3
    command: --web.enable-lifecycle --config.file=/etc/prometheus/prometheus.yml
    restart: unless-stopped

  node-exporter:
    privileged: true
    image: prom/node-exporter
    container_name: syno_node_exporter
    ports:
      - 9100:9100
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    network_mode: homelab_bridge_network
    command:
      - "--path.procfs=/host/proc"
      - "--path.sysfs=/host/sys"
      - "--collector.filesystem.ignored-mount-points"
      - "^/(rootfs/)?(dev|etc|host|proc|run|sys|volume1)($$|/)"
    restart: unless-stopped

  snmp-exporter:
    image: prom/snmp-exporter
    container_name: snmp-exporter
    ports:
      - 9116:9116
    environment:
      - TZ=America/New_York
    user: 1027:100
    volumes:
      - /volume1/docker/homelab/prometheus/snmp_exporter:/etc/snmp_exporter/
    network_mode: homelab_bridge_network
    command:
      - "--config.file=/etc/snmp_exporter/snmp.yml"
    restart: unless-stopped

networks:
  br:
    external:
      name: homelab_bridge_network
  default:
    external:
      name: homelab_physical_network
