global:
  scrape_interval: 30s
  scrape_timeout: 10s

rule_files:
  - alerts.yml

scrape_configs:
  - job_name: services
    metrics_path: /metrics
    static_configs:
      - targets:
          - 'prometheus:9090'


  - job_name: synology
    metrics_path: /metrics
    static_configs:
      - targets:
        - 'syno_node_exporter:9100'

  - job_name: sonarr
    metrics_path: /metrics
    static_configs:
      - targets:
        - 'sonarr-exporter:9709'

  - job_name: radarr
    metrics_path: /metrics
    static_configs:
      - targets:
        - 'radarr-exporter:9708'

  - job_name: nzbget
    metrics_path: /metrics
    static_configs:
      - targets:
        - 'nzbget-exporter:9452'

  - job_name: transmission
    metrics_path: /metrics
    static_configs:
      - targets:
        - 'transmission-exporter:19091'
  
  - job_name: pihole
    metrics_path: /metrics
    static_configs:
      - targets:
        - 'pihole-exporter:33302'