global:
  scrape_interval: 30s
  scrape_timeout: 10s

rule_files:
  - alerts.yml

scrape_configs:
  - job_name: services
    metrics_path: /metrics
    static_configs:
      - targets:
          - 'localhost:9090'


  - job_name: synology
    metrics_path: /prometheus
    static_configs:
      - targets:
        - '192.168.1.20:5000'