apiVersion: ENC[AES256_GCM,data:gjw=,iv:7phMefxhslzTN2hZjqlJPmBl2bnLm8v+42+hhr9oT3g=,tag:rUW720D7OZqgsqN9DYN0RA==,type:str]
kind: ENC[AES256_GCM,data:1Vxo1tmr,iv:dD6lFZQseuRk1YLfqAMsabDjZEDL6DptYR0cks6VndU=,tag:e6+fBsFTe+1Y9Aa/vO8djw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:OQSNRzWrBFAWfCYQbUSrOlNlTXGhfFCTFIlVNmA=,iv:N2Cx7R5J57tFimGkhYVFzskYhKDBav7/Va7DGL7CHNM=,tag:No8Ovb/5HQW18lgNpAkBiA==,type:str]
    namespace: ENC[AES256_GCM,data:HxO+CIonC/F77g==,iv:ZrcQGmh2OoPiZWd1m6kmyRbYF76qJ6mp6MihCNW0Jd8=,tag:kx0NK606k2rfr1DPbSqnyQ==,type:str]
stringData:
    alertmanager.yaml: ENC[AES256_GCM,data:0fSl+FwSr0J4IiSukEPmEj/ugEQ+sPVAsSw/7xYQqWd+cRdRJewSWkMUH04wXbYn+ed69LAO1wyynGFts1qo+xYFSo43o/iyDuI1UlBjvp6fcDVevkV+KLsLQuOcIIJQNPNB2jfSMm8b2ohRWfdr8B9QVjwMZ5TALeorBaNYvsgIzU2cxxpwtqqC9dzJtl3OZMdwnhMhElvAjJtvoDJGxPuhBfNMMzZAHByBez/4LDdOn0Wk4sVbWpMbxgUvZFN+J6SgC0yRgAW+m2vLkEt0XgmkY1GkoH2Yife7IhZzZ188JrNs5I6AQbholiIQSM8RaWXivI/LLOToewnhil9Sn7XeNQYbIOSUDE9NLUONe0LHraseDmiNBHPBaAlWm8X6Bi9jsKq93JQMzs6jwrdRJrk1a7PDa/b1n0Ls7wfoLizSTJQcEtImWIOUQYCKyJod++0AznihGumLudrhKdRf++VbAUtPIm2tMhhxjm7cEdbXCHO2/Cp8+cXXwqFC7f9ENhAMFnp/FKL6lCabioNs0Ki7Y394Us/L3zxTfiDBQMHsbe6xeYAKaZUYTs3IdhirXAcYcPYAcMFBlwNlRxrdwcT0atYOuZy20ZJKV41U3ZDI6T14XVDfxX66NFdb6Tgbe70w7418G5gEy0IG+DhId7z7WCL/Xh3a9qvK9aj6tgIaidqbE7e31UdcnquyAIY8RRlMT9oGdU+yMC4M8D5twvTjxjbYb1TEnhuoOLmo+kdOLeNDIQ8qCMVvzatK34bpyImLl+oTZjzO+/Q9DJ9NMMhrarrk5ncx0XUkhBohsMZxQOEE03hOuf3AIqisSzJmVXQGm5ZkzsepgeUnTVFVTQJniqGNTLP2po2Hyle1GLqXRbjmr6blmqs+Bf9Ivva2OnwqmBap377X6dLv1GxZzgz6EjQdSEXLh96lqvHdNj8Vlc09TVmw6bB1J4yUPGZs0W33XNVSkGq3JUw4IZOJMEHyZclR/zjz4s+/0uq+HH824VstPXr0E5AAWwgSA82svpO84dDo7KINdwqaIgWVXfF9,iv:lven5meiiDT+1kZMlhpN9wEZMrQJ10nDGI03aOHK5WQ=,tag:wLFQM3vVR4luoBjE/KHcaw==,type:str]
sops:
    age:
        - recipient: age1qntcdwtxrfu92lhj2nzhlc3uqt8nxks5vw7rd23w2cj7c0qyuqqqmey085
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhWUN0M1cxRzFqcDdnWDBs
            WWZVLzRnMlpsOStHQ2ZIVU1HN1gvZk56VUc4CjBUMHRBZ2JTaHJ6anh1YlhpUDlC
            dTN2cXZORTN6ZitUengwbWxKczN3WFUKLS0tIDVyRWpLSlQ0QWFFNy9zU2hQT3Vl
            S3dvWngyeHhwbERzSHlzUWhvNXc5VHMKFOuyywQ2MKo8PXmsKdTUUbd05VZeT86n
            TYe/nASO6TMPcTTdM+gXqauBLglEhkjqaXVkpu+jNT6vKzUlspKCqw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-24T22:47:49Z"
    mac: ENC[AES256_GCM,data:tUvAco0jK3sx7H0mbeQDiYkiFhOjiN1v1Bo8ISo0HZhxjdKwt+nFz+QWH3niSFplWhocQ9Xkb3YSz2FtlpdBlN/9NocoGw8HG37Pgb0ZYNPNnvNwXGRulDbxdsELP8IduCD1Tyig9pZ8MBovOb9g3d3vJ2QB/6d/RjojKGmbdSU=,iv:ap0G7j5qKWibgY3LHg0OYjKMeDBQlOdRMQT3yl8rTcA=,tag:5PlHLCPiWMNKGDnYpm3kng==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
