apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-pagerduty-config
    namespace: monitoring
stringData:
    alertmanager.yaml: ENC[AES256_GCM,data:YcVa6Munx5j9SOHK7MGNJ+ZwZ8SBv7zWSsTcCqkGPgM/W4BBvYKU1ObKBimTT4gXWub9qCHmzc8nypw0Q4d4nyzQhHRxAHclW6Fxi370u1Q8L52OJ/2HwVXQICc2YoIx0Ixuf1uUBe41NgTHyIctLWQpoVkfY/RdAxGX5j+pZbNStv7UXTDRELiMw74mGift4Qs8ZxZlseDi0jDKo1MFF9MI/qPLzMiYY2PIE7gZrPeQCh9YojSMbfqdKP4XNWnsIxxFGcALcNMYO8TjTx9inPsuJxuwT+yOw23e6KthZkqBoPDEDW1jn8VKW2Wutj1xIj68VV0NKVnsH9QRLTxwMK+XeMG2+2V4FzbK+R2cLKX4V5oko2/W99laDi+BJskgy6ATa0zJUw0mCUb2hdTwvU0JgcUR3LCIEb49OJM8B/A2szWqtIpSpzyGMvwtnS5KyD4ZOHh1Ol0rJZIj1k9vYzPsm4lNS5aaDqYmSqGjHHwim8l9Q2OBlAgo4hJgSZUVntfdyMDbeOoQg1Yg45x6XcjxQ1Wd+8T7tZ/x4JXWIiyskCY1SSmLe/ScHdnwff7WRK4+j7B7P+o9XBQzFcgRJ9TCOmYk+o8cQHXDW/sN8O75h6kwxi9fVM7VDM5RD50WQFgYNspdovOp30D5hMbUtFGImbjojo9iGbqZYPojrxSST6PeTP8oUq1Pd+fhBcepFjncI6qi5APyNTv3WaGBEzHXCsbaOi2sK6MRjYs3f13llEqlFmIycQ==,iv:RgXziCaKRkPpg0lScITFZb2t9tamCamYHeR9pdf+5wU=,tag:P5FbZstMycaxSDPQtqevEA==,type:str]
sops:
    age:
        - recipient: age1qntcdwtxrfu92lhj2nzhlc3uqt8nxks5vw7rd23w2cj7c0qyuqqqmey085
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVWjNoRzBHd3NKRngzSXpv
            ckNtbjVlWXNSNGRRMW1xbmQ5RExQdjBvM0ZNCmRVNUdRQU45MjhGSkRHMkF1WWR3
            UkpNTit2V0xFNGg4MnoxbDdMV2kxeVkKLS0tIFcxUUJlbSt4Z3RJMzhobEEwd3A2
            dHI0NTlWbUV6bytVR2lDcU9RMjJjOFUKLlaEQxrqISNVMTQVrngN82Dev5/Mcc+n
            w8SJNDyVsVjFy1jUZqNFuvkAU0NtW19VoFV7ZfhOmDLuTkxrSsAAVQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-30T21:22:17Z"
    mac: ENC[AES256_GCM,data:LjUs4Tj+jCr2TRe4Ss08Scr/PadgIDwVN/+EYzLVo/kCGI88wx6qIw1ZjXHxAJ2dWKBOIO++6jl9heKVogXzXAVQa0m8bE+DrRUG3pd7LULuQSKJYOnaMFzZAGTFxkx8puBhMsw3O+fw6p1lnkR6XHZuUmaPP0G7dhcpvzCbGbQ=,iv:WAigpf5XZ8Sx+UsxF0KykkrYjG67ByfmZGc46c/jCQA=,tag:SaB8Hca5yjei3RMKmv0l6g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
