apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-pagerduty-config
    namespace: monitoring
stringData:
    alertmanager.yaml: ENC[AES256_GCM,data:3OWQlD0SFbjoezDos0IuwBy9Ia9VTzSJ/oqb1/9tZRsH0q8OXse/hbARabKaOgabK7xcGzIaddU6F+ijHErnSVhLtnl5vvcIcsTpKBkw/7X1KfP9A77Dkiw5lq3Xto0fXh/P08329FzsVhkEB63wKp7UxRjbaYCWdBg4PUqiiUdp5RYpoJsu+ukmE4fi5DSyqarF+8IFGpsicRi0fr61hDTulWLaJnQXjUm0WBFNHfmd2KsIDKXPAaiDGiCIBx+fFmfu/wGGUmTp2dmwqzfZhrX7/GLOQR74WWhjvVmeHjhWSHOlkJ9FeN4k7t44y8HmHUs0tPZEHTGkmwjr1w9M9vUJ6QEz1DHAkdZ4QgTOMluk4tvkqpjAwntuwuIiZyb5PGNtlmFvgYy940WiRairjqw8A/OAJKSC3g6Fye5rzjj86Ds0GKxwE4umk9y5R6RqnW9hvhEpwZgajgRFXzF2uGKPipnDJBkiybyXsN8UbxpQ6JGoqW4MeXUzmw7fLeQSsDy7+73LAZeXEcEpRMr5RMbkmZ5ECx+ro/mLryi2ydSyG/XKN5UoPSTlX+tbryxD6i2TzY7gkSMnYeMK3BpRj6wyO9kFSLDu8wrF1u/OmNC/+le2GF5HSo4X+x6pSlBBbAk8R6uMkHmuS8zGqGCNN6g4Jntkgg6WYwmEhaVt+xDX3OLxiApEmbIk0UquGZI2vWvZc+39kZkyA16GVmtd/aH6clgFz9ZgI0lVlt/DbVEUSF+bwFEnBrKmlp32Y1zg+RmoLH7TVlWiXhr7QlKWVT4HhI31DxqSqQ0AMaYZWBqPKmTpo8erKxhR6ewIxflLC5RLgQgFx5mxQFOrNZpTU7k8jwveo5hK2ydFhMLuVqlHCdpy15TSCzt1HXNyv1M3RtMPvrj5ClWCNds6APTaOWnblmGvzd0MkOmcYqk872d+lEGbwXAdehA81BxvjK9rUbrB+/D7F9pvVVaTcJnOYl4R5Ct68PETCU/wQ8ZMlnZHowbKX8PkvKCXEUKX1oO+2TqVjG8lvD5rXybDGn0Ruu+5,iv:ubPl/m0xD2/C2gnRNfz9mLsHijnZOqlU7/cPGFBGb1k=,tag:a2Ist/U3q93S/0EuwiB6hw==,type:str]
sops:
    age:
        - recipient: age1qntcdwtxrfu92lhj2nzhlc3uqt8nxks5vw7rd23w2cj7c0qyuqqqmey085
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuTGg0bXAxTVJaZS9HQ2pu
            N3ovUEcxc2cxY1hzc0pFeWEzTy81NVliMkZJCkFVUHdaTUVLbXE5K3BGU1hJaUlE
            QVFyMmkva2lCdnRSRWNQZjJJY1BKNm8KLS0tIGVKWmJPa2ZnNlEraysxYkNobHYr
            SkRaZXdoNURPTDBpN1R1R1dzUUxPRUEKw41ko6poYPUVbS062mC56j5htl3S7rUB
            nT4lduwjMe0dZiO69tqzAeX9mj+FekWN3VGK1sJ1MHvMXSy+yizKAQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-02T00:50:53Z"
    mac: ENC[AES256_GCM,data:b0RXqR2MJri/ybL5jhKfhDZEnKP+puDx1YMpF7Rvf7FRm0sXxEtWXCt2nq5J51lJiZ0NFYNlVLoMVvDQ7d2JyYN2NqYQq0dWWjc77MzA32wch7u0KxZ3qZwCc3Yr8rcMF4o3Oa2eX7/3NZeVFTf3LxULr/HX68wDStDxImCdrD4=,iv:bhAL6FqwFv97RTBJSdOTqaQeac+3gw5ICf4RfJMW9q8=,tag:nJO5c487+x7bNIXTw1aStw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
