apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-secret
    namespace: monitoring
stringData:
    admin-user: ENC[AES256_GCM,data:NlCyjgk=,iv:9TgHF3v/T6SIdzkuBoa5o7PdBwMVpunHNZnsfL4bp3g=,tag:YoKpQDpV+J5X3XfRuKUgfw==,type:str]
    admin-password: ENC[AES256_GCM,data:cDAvSvOfGIDltMTG2FhnLIGdpnHVyCIfO0SsrzbemzQ=,iv:ogx+XaI3DB4zyMoyXEWsHm6DxUpwMjdYRuR6S5/CQXw=,tag:hdIYiz9EHRMrR1RkjisrzA==,type:str]
sops:
    age:
        - recipient: age1qntcdwtxrfu92lhj2nzhlc3uqt8nxks5vw7rd23w2cj7c0qyuqqqmey085
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvMFhmRUpOdm9MYjVnM2d2
            SzVaWkVzUERVY3ZURDdTbWJRY2NVaDNibno4CjQwTzVRUTNxL0k1YnVDdDFvc0Vo
            M2l2TDlxWVp4Uzl6Z1JpSDA5bDQ2QUEKLS0tICtlNXpvQ0c5RTJVN0wzM0h0cmRk
            dkIrQ2VraThVaHJ5bGk4aVdGNHUzT1UKJVRT0CirsX0NNHCpRTs/R+FwYNUdVyS9
            SmYo6mEtUUtaVRBZcGFaL/euZT8Ko8y/yTy/fgNA1jo63Xiw2zts2g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-02T00:50:53Z"
    mac: ENC[AES256_GCM,data:q6o+ghoxu21Rukxo/Hzh6lUbMsNtvTau0U3UYi9w7ZU42BeTHxeZLBbUNiM71K9183qi6tW0iKNf2TPGAWY449DuqANhjJpRC5KITtyuFmpppbS25H5KIH/bHDEJVq/McVij/DFZhvoDpizDa3UjBguCWg0ez/YsOtolGgUEiMk=,iv:lTptwrwBVWxCQXGv7AxfdYJlJqsKfhpIpv9+vlu4/4Y=,tag:XSqmwhECEZCo7fVzXmrYlQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
