apiVersion: ENC[AES256_GCM,data:YEU=,iv:MBNwU17q49ycuBRPNHNQXliJb2eYNkmB0APtQMew3V4=,tag:O1WSi4p0V1OCHH1OElbxUQ==,type:str]
kind: ENC[AES256_GCM,data:XW7liDP+,iv:morEyC12sidpHGqU9YR1yCoz7OA/Z5KiKA+oZDmwl8k=,tag:rJzFsBzNqTn+fIy7dY0iWA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:fTzpFGJ4TX+YOqhFHb13pWmCSA==,iv:8F36pAMduM0Z7b1kQbUWsTSYabxEuiFd1ObkA2KTxjI=,tag:uovjsew2K55ki5a9m7OaYg==,type:str]
    namespace: ENC[AES256_GCM,data:3nYYpcCMgOuiBQ==,iv:sI/T07gUuhhDxxNAyiBT5pqRl5DfKtSNZgeNZBGfNns=,tag:1HHqSM5aD+oyo3eVZZ1cOg==,type:str]
stringData:
    GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:yi36QuVmIoPW8Qgdw1AR1r2HLmQkjud4BmTdF1oWX70=,iv:JWhUhWISQfy0wb1rNuA4SGmDgwPlohG2i+ItWRv/cDk=,tag:dVgw6thgPxfrIx4Ui84yqQ==,type:str]
sops:
    age:
        - recipient: age1qntcdwtxrfu92lhj2nzhlc3uqt8nxks5vw7rd23w2cj7c0qyuqqqmey085
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzeDZKK09SWFBTbjNZcWpG
            Um5kaHk2UitWUGNZNVVYZzZFQXB0alNNc1RjCkxuV0syVEIwZ09aRTg1Wm5LaWs0
            RWNUbnEvK25zaXVzd043SnhVYkVsd2MKLS0tIElEWWNrcmRtSjVmT0NGTTdMekht
            Sm5CUFBRMkpCTUJHT3F3cklDWDBHaWcKhH/JmuXEbDvfBKV0J3p2uD9ETrj2BVln
            XWhmn1WTqAHMTCSdmAaBlDuSzrEVPsSvw0jK0jXGfsj8W0jSx9FC2g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-09T19:37:32Z"
    mac: ENC[AES256_GCM,data:v8+JbvDI7mCcJHX/JWVFuOPu4xiZM8betVov2v9NMFrRQgu1tebmGKvuWpAYp0hbOYFdyQKv4njnljVV/jd2Vmrdk21PN8RxeipapaGDgFjAxjSTHY2bmzfQmgA6V613Lc/NdkkIG5huhn3VrNW6eu6n8drCaCQO9dUqfISIbYo=,iv:UlJm58EB9a/zA2sk8G3YpmE54TeVAZM/0KGVUhj8/8I=,tag:onKPWAF6zHXcwAF+TCoFsQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
