apiVersion: ENC[AES256_GCM,data:TZ8=,iv:AjpJa+Sm74Ay1d0/M6eeXPAmueX7ITstULRU5/gPFbs=,tag:r99tGwW/FgppgiF3joywHg==,type:str]
kind: ENC[AES256_GCM,data:WVZ+oE3i,iv:Mh5OBHz1jbFP5J5Fxjpdj9GZERyY2ccTiVltDk6/6Wc=,tag:8aRdC5xeVNTIYLV5JgtVeQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:0KxSyClIOQ2OdLBc4LCvZnJNRAc=,iv:xk+HFjlmCzoowMTorOBj17JYAkrjbWQbkGjJnJG0OCk=,tag:av+4K49KEdeDCllZHgXQAQ==,type:str]
    namespace: ENC[AES256_GCM,data:GGOvLTKheS/1zQ==,iv:r53tEr+YIVxVMhF/5Sme0suWTnFGvcFoLzEODdt3S8c=,tag:NESR2M/bAhpITSSct5c2Yw==,type:str]
stringData:
    admin-user: ENC[AES256_GCM,data:viJL3LI=,iv:b+FOljBhITerHLy397/rDSPnszyzOhyoEqP1X830SnU=,tag:3MPKnJhKVCKbcq+1ffmQTA==,type:str]
    admin-password: ENC[AES256_GCM,data:2GjopebGNqKfRNEN9G+tMsRBPxOMYpKpBUQTAWTgX0U=,iv:PeYvCKYcEzW9mWaKhNgLKP6F1vG2MIhk1FhS/opr7xY=,tag:kOYiqjOxffu0GeMTlch/qg==,type:str]
sops:
    age:
        - recipient: age1qntcdwtxrfu92lhj2nzhlc3uqt8nxks5vw7rd23w2cj7c0qyuqqqmey085
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1VjBHZWwwWEV1bFFraGwx
            V2R1V01rcVdFbGVTeEF3WGh5eWUycmVoWVNjCnNmQ3R0dTg2WXFwdGp4SkdDZkFO
            RlZiK0RRR25ua3RpbFFIWDlkMitmQmcKLS0tIG9mdVVNTUw1MjhvWVVoY21lU2hD
            SnJ5biswbCtoVzJzQ09WeE1Rb2FaZ2cKq9WHEu5RPMS08TLziOvLlTZCArCvCbOk
            A5ZUChIkZg3J7Ig9wkN5HNMruYr5PCGIRSpvch4oYJKeWOiTRRj5tw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-06T23:22:29Z"
    mac: ENC[AES256_GCM,data:vylwu6ddjTDf2R2IKHNf2mcBReIKnV+YacfIZHXo2II8xvveBtFwfeTKWzBjPhplZCbGOpHfz0YXVzk2JHG8TIu0CN+8mrOjmMhNyDF7+uVFIU4sF7CTrVb8KrwXZR7wtXEa+k6QJ9Mawrhttax/STYI7tbRYfOilHchVprvRAM=,iv:0ZKX/obxyiw2dgL2bfzVePmkBTzZpzenlXzWcywk6fE=,tag:OigN9eP1D494pRBO4ptygQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
