apiVersion: v1
kind: Secret
metadata:
    name: grafana-oidc-secret
    namespace: monitoring
stringData:
    GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:QSM8/IVA2YCMYsP69xCr21OB769OdqJyE4EHuZF4WC8=,iv:CURj6RatT5iiEP92q2jgOnB8kIxEypyCRZoO1ISmB/Y=,tag:8l9PL+HKRkKmUEm93ICtSQ==,type:str]
sops:
    age:
        - recipient: age1qntcdwtxrfu92lhj2nzhlc3uqt8nxks5vw7rd23w2cj7c0qyuqqqmey085
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmcDJSMkExRWNFYk84c0Y3
            T2VrS2l0N2VXeFRDQlh6ZlVhWEVhMHkzQ2prCmVCQUp2OGxJRFB6U3JTQUZ5bEdw
            azZTbjlzaHVRbWJ4OWRLejJwcVdHUFUKLS0tIFRtRVdONC9MeUlBYWhkSVgwTkNR
            ZWcrUjAzTkRZVkJhWFM5ZzlVdG03S0kKCiXCQRzODoh7ZsxlHqlrp+q/GUMd/xf5
            IZ7FL7VO1/jpJoAxahWK6/vnzyLYjXEjgPlF0cDYs9O5kyZ1PMoXbg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-02T00:50:53Z"
    mac: ENC[AES256_GCM,data:/7J9znTXZwarSSBqC0g0BDbSOAnQ7IUL7F6COGkLMWuvmKi7PR1e/ynBc9jajf1pDiSsP+pq0UMNb67mbZj/SSzJhRy1J+TTQ8ARCeGt/VksDZClR3qW0v0A/hP6mm+vYn+EqysxG+L+uHvR7qexQwOj8xsbErfho4e9LgNghS4=,iv:+hwORlkUNduaZnPDMyPm7RErBU3ylqWf1dkOlvwtrho=,tag:KqDVZyNEsYSHXVrnpX9bKA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
