apiVersion: v1
kind: Secret
metadata:
    name: grafana-gitsync-pat
    namespace: monitoring
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:WOJLveXS3A4sy7iSbBxA25JNwUTZSx+fiHtp25/o95oyiwR+ZBpVdHLXlyTygl4LGfFLeju2uDR5f9MoZukvkXfPEdppT9V8RbqBktmFrmhEpofI4VX37kt+hbrg,iv:ZB+91QBTeli6PoFMkm/Rx/8yI0GppN5DaS1FM5VLgr8=,tag:G7yjy5pgmVafBb3xd0AhYw==,type:str]
sops:
    age:
        - recipient: age1qntcdwtxrfu92lhj2nzhlc3uqt8nxks5vw7rd23w2cj7c0qyuqqqmey085
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxUVhHMGM0SHdVdm02eE5h
            SDB0QWRjamxDMEp2NVdlK1Rtb091YU13QVVZCjd3all3TGRLWUF2Umxvc1NjZVZJ
            UllDS2FnODNjT3d5bHhFNEY3SDRrNjgKLS0tIHljalpZbSs3YittSHorUTN6OER2
            dHo3MjRpdXk3cjRIbnZleDdrT3RtdncKU+SbmmrJt2cc+cf0T+mZkdr0FQMlMKuE
            1CUis1+8ukQ61ygAZHUiqGypte2zEQBnQ3fpBS1XsCU12hXcY+E7BQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-02T00:50:53Z"
    mac: ENC[AES256_GCM,data:cxjdQrVyv7UHyDmUFzAhKUdUPXKkHLLw36cmETVVb1tura8SdmZ0Y29IrYlKftmOs/VcWbOPeZXDv8xawqasxso8zl09+2QJ9S6atxFbeWwu3nwuPxHZyRXrbgADaxJIc41u16UMdi7sypiFaVDuvzFxdxtXgF0cYr73juXBy9Y=,iv:ZwMhvdD5CYSs1McPFZzzRKbzRU48o9M16/w6YbG+U4o=,tag:7lel/vuiyM2fhkjY4osjog==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
