---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - grafana-secret.sops.yaml
  - grafana-oidc-secret.sops.yaml
  - helmrepository.yaml
  - helmrelease.yaml
  - authentik-middleware.yaml
  - scrapeconfig-synology.yaml
