---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - grafana-secret.sops.yaml
  - alertmanager-pagerduty-secret.sops.yaml
  - grafana-oidc-secret.sops.yaml
  - helmrepository.yaml
  - helmrelease.yaml
  - helmrelease-blackbox.yaml
  - authentik-middleware.yaml
  - scrapeconfig-synology.yaml
  - podmonitor-flux.yaml
  - prometheusrule-apps.yaml
  - podmonitor-cert-manager.yaml
