apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: authentik
  namespace: monitoring
spec:
  interval: 60s
  module: http_2xx
  prober:
    url: prometheus-blackbox-exporter.monitoring.svc.cluster.local:9115
  targets:
    staticConfig:
      static:
        - https://auth.homelab.properties/-/health/ready/
