apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: tdarr
  namespace: monitoring
spec:
  interval: 60s
  module: http_2xx
  prober:
    url: prometheus-blackbox-exporter.monitoring.svc.cluster.local:9115
  targets:
    staticConfig:
      static:
        - http://tdarr.tdarr.svc.cluster.local:8266
