version: "3.8"

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    environment:
      TZ: 'America/New_York'
      WEBPASSWORD: admin
      ServerIP: 192.168.1.2
    volumes:
      - '/volume1/docker/config/pihole/:/etc/pihole/'
      - '/volume1/docker/config/pihole/dnsmasq.d/:/etc/dnsmasq.d/'
    ports:
      - 53:53
      - 67:67
      - 80:80
    dns:
      - 127.0.0.1
      - 1.1.1.1
    networks:
      default:
        ipv4_address: 192.168.1.2
    restart: unless-stopped


networks:
  default:
    external: 
      name: homelab_physical_network
