apiVersion: v1
kind: ConfigMap
metadata:
  name: qbittorrent-config-seed
  namespace: qbittorrent
data:
  qBittorrent.conf: |
    [Preferences]
    WebUI\LocalHostAuth=false
    WebUI\Address=*
    WebUI\ServerDomains=*
