#ENC[AES256_GCM,data:QxAC1yhigQaEjwWC9b+L/QblGm+AEjR5bQ7gXcRkDVLzmDzd3zYSsJzmuAOYEP5HQOmhTdZMUW914TguCH3O30Z1GH/3/Cl45PTF9AfIXgJv3FRzQzjYzys=,iv:xPJ7/PXmiF3EWjgJRNm/XV7DENIGfxnGtgyBa0OSTao=,tag:xR7O29JrVAn4y5rKrne6/Q==,type:comment]
#ENC[AES256_GCM,data:Tnf1jqtMhmtayFzMaW/D5dI0n2jWWjc1typW50NZ7PiFAH99Pk929ldZ7y4UhnFXtis4TrkULGIutFjZUoTz6q8jPzV8FoUaHf99pVzPI3XiH55OSEJPSPWl+tq5,iv:W5t72VFM5GFjp3/kDx+25lwQz+y+UrdMamjgNYNXb2w=,tag:2VG7BJs81hF4E28DZjHIpg==,type:comment]
#ENC[AES256_GCM,data:0rlVt6wiDzP+7GfvTKOt1dDYbKeFRYJHC80O40uWGF/ZkQWR7Cup+9JyTxGb0FlPrvVKCJZBhR1vetGZrcj6VOCJCxVBdVnKhrjjEo5RjZ/ygCAD2sYNeq5Q,iv:o25kZa2UWPwLNq9JN6cjHAzTurmr4OBKT2/cmxBh6dI=,tag:ME4iF075yV/WOX+4GPBImA==,type:comment]
#ENC[AES256_GCM,data:rqG0HhjmAEN3ePqpd5CLQr/BcjLDdoIw0EgQCJ2gehCmyep4i/lqm/kzb4rb6EMNV3YN+lU3aV6L9stDcjVWP2BXxk66Gnw8Y1KUaOsD9abL7zLA2A==,iv:DZ1JIMcpoe4ejBtGJPUOxngV2nUGFlOoJrukjGiy/ZE=,tag:TH2qamaB4m1Z0rN93HhgGg==,type:comment]
#
#ENC[AES256_GCM,data:yo+0r1q9vNsCzNj15yTkxYucpS/sKsyDXn5KgKwropHA6WsmS2eIYKPXMVEtH297AuW0mUtYBnIld36AeRpWSp9S1yXYfoC17vT4bw==,iv:iFvqyQsbaeaaKIHOhB2EnDAJytMJ1L/H6MxXtgpdloc=,tag:61hqxUJFIO6DWnadkLZfXw==,type:comment]
#ENC[AES256_GCM,data:SwGXsD/2pwGJjEiUrYQe3uE2CX7tZu4Hlpr95pFU/KHDg8yvp7EChNqqUhRme/3GksoMOUs=,iv:5EbsZPJEJzGdezUK7rkYeBGFdQuc+GEGzsn2ahTbIo8=,tag:QWbt5ZW7eRnpHviMh5R9Zg==,type:comment]
#
#ENC[AES256_GCM,data:JDxXIaihliqphE4=,iv:yOuu+IUMeztpj0GiyU9nZQEqCpunr0YaOthFkYvrZ9E=,tag:OmaKFeaoprXYPJN118bx+w==,type:comment]
#ENC[AES256_GCM,data:T2E06y/SLB965kHB1/pbB66DYhuNs+7VhpmZwbCsNJ2uKCAstxka57OlElt5sTllIIizbjyOj31YyfemH9m6+vnoQ7NVL6JQXQ==,iv:6BEin7d3+VMRFpkj/hugHF/TWtkPN9i3GMnpQA8HsYM=,tag:b1tCE7G6YQt/4jmEYUanTA==,type:comment]
#ENC[AES256_GCM,data:1hnTV7YMVVzlYd8y6LXX6owcFe+WwYihrrVTsIOrHDoa6cae0XnOCnH87vTY0vpRAawNMnYzXjMy,iv:HaqyaTx3KRNQvcKoXmAnBnEn2ONcNsX7QRoo+4QbC6o=,tag:G0upHqpFVHYoybBEQFJ/Xw==,type:comment]
#ENC[AES256_GCM,data:6bUsGx/zQWXdiemMVeuNXYeC2T8teFjwpRYY1du+hemYYs/kypAoOG0vNGV6JXQDu3LfcCaVcab0GjsO/WQTiNwzW+frmlnXCj8IPAZ6j8WCEHYMR0TRCEY2mpz32uSyr1lV0iFnYT0rHPc=,iv:C/OB7cgKgGeeG1s637UBzzim08la/wk9Wd4XFAjxx10=,tag:xcsmFX8e/4nDTg5Bm/X6KQ==,type:comment]
#ENC[AES256_GCM,data:vqQAyIMOQrvONsKqjI5BQ9iuVkd9GJ6IazA+QwHZ+zcXgNSNM++urvQR57z/7mGnODHdF0lE2A==,iv:n1Db4RK1LyPPe0AmrY0HewuwmO1C8OgPRXglBvJzNTA=,tag:O1zSWr7dXBLiRD1Hn4U8GA==,type:comment]
apiVersion: ENC[AES256_GCM,data:LEo=,iv:Q6q89IHK7jZTBXdoyz+01d3dqTERBfYOQ6QQ2G4Gvhk=,tag:oSKft8IgyO04V528ewLPVA==,type:str]
kind: ENC[AES256_GCM,data:+Xz370nb,iv:REBitlKUy0luqi+lxEorOaVnXwfuJc6P+hLcpfdqlbY=,tag:fMs9pqkdT0PvtmsvMujoGg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:s741itDP3+5O8ATO0jd1FZ2f8A==,iv:mQEDVS6b+zdJbZBu8EuBlDsLENQaH0krhJA1RsOYtgg=,tag:mMVqH9aTbyvctt5ctyl6Ug==,type:str]
    namespace: ENC[AES256_GCM,data:iUydrG/O31zhONM=,iv:ZS1JDwXSSbQijtLN1yChnZrSThMt5QmQwJjnQJiagyA=,tag:4/AWaiZQvfessrBd3Qeq5Q==,type:str]
type: ENC[AES256_GCM,data:ELgjkHpY,iv:3ldqDbjB5cdXLGwf148Lewksfif82DKQSgf13pafn9U=,tag:74SnCki6vOTxdvIJTHxgfA==,type:str]
stringData:
    wireguard-private-key: ENC[AES256_GCM,data:vbd+/vEa/FYhDj8KvnovNJAZh21ZbVfwwWnbHw66A9b3ws+T7hR7AodiWQY=,iv:useKuXUU5hTU6a0nr00BLvqlyI0+IRL/Vo53tIFcmBE=,tag:of/7qcW+4XGUuPdBqajjaw==,type:str]
    openvpn-username: ENC[AES256_GCM,data:eZcZt56WZ0UNa8WHU/Sc4sztU/WCdwU+,iv:igmzPPRWHX1rWA2UzFcFttrz0CiaI2dVR/aaUNeTieQ=,tag:vFhQVFDS+9ZuZV+CIduxyQ==,type:str]
    openvpn-password: ENC[AES256_GCM,data:ogV82l/a3w+AZ5aVt+Q7ecR7EcOWyjwy,iv:knILmGw1/UPReD9yWeUPUGN4fioe8c2kMk+w08NhtYo=,tag:EXac9cVEirvGchnx0dOgRA==,type:str]
sops:
    age:
        - recipient: age1qntcdwtxrfu92lhj2nzhlc3uqt8nxks5vw7rd23w2cj7c0qyuqqqmey085
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAya2JwS1Z6RDNFNDJiQklP
            Q3U5dGVqZHhQVWY0cXh3cnh6OGE4Q1FPQVRJCmJsbHBjdU8xVWI5Mm5TNEgxVWVu
            Y0lyWFIwSW9qSjdWNEU3SnRlc1IrTU0KLS0tIFEvVUo2cGxlZHhVQlk0QnJNeXFZ
            RjYrc003aXY4R2FzSUtuSWRQUk9RK0EKCiprQ35x7PMkJBvPjt7lyh9hP4fhXkrc
            jHlAZJsVyUUXHFVwm0m8Ffr54NuJid+K/fdm5aKkgwW0MaUcqtVbNw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-29T18:32:25Z"
    mac: ENC[AES256_GCM,data:C7CvYi+DHNxd2sAby09YOlwpZn+XYcP7x4UZv72e5lhrfaSciln1vK2bQNzQCtD4zvd/XaEX8KFh/nirNMLZzXNLhoozM65lMWLvveKoXjQoXdJXukDn77f+RqkiuLhZ4W5kGfdveU78SkmRWEGZDIbAJw67+Xx2mt2eC6WIuYY=,iv:CSzYbBN4zxjuwvUTgkx2ciYBOXBxsRmAW+wn8FqBK7E=,tag:mkzkNuQ2qRGVVGTSXwpagg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
