# Encrypted SOPS secret. To create from template:
#   cp qbittorrent-credentials.sops.yaml.example qbittorrent-credentials.sops.yaml
#   # Edit stringData with your chosen credentials
#   sops --encrypt --in-place qbittorrent-credentials.sops.yaml
# These credentials are used by the prometheus-qbittorrent-exporter to authenticate with the
# qBittorrent WebUI. Set the same username/password in the qBittorrent WebUI under:
#   Tools → Options → Web UI → Authentication
apiVersion: v1
kind: Secret
metadata:
    name: qbittorrent-credentials
    namespace: qbittorrent
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:5XrQ2A==,iv:+tXt8zix1VszA7F+O1DEZw0J3wSt4PlVcNfd+7RKug4=,tag:vaV+6ZWrCuHe0/H4aNFr0A==,type:str]
    password: ENC[AES256_GCM,data:gJ6rqKOJjgjLcCq88Q==,iv:ahvITkkhUAuIslQ+6HCVubvm0QOtBQbitY4vW9z/xcA=,tag:WiK8hc75BzKzLdVt3E9+sg==,type:str]
sops:
    age:
        - recipient: age1qntcdwtxrfu92lhj2nzhlc3uqt8nxks5vw7rd23w2cj7c0qyuqqqmey085
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoYUEwWU93U2s1RXZlQUxP
            UVZYNWh4T2g0ekt5REtSOG5FSXF5eE10dDMwCnB5WmlVbWE0aTFETnBSVjNKc3Fk
            SWxGM0xPWE04Szh6U2xSS2I0ZTIwWEUKLS0tIDJEMjRxNno2MWdnMGZWRmVEV2t5
            cUp3UjRPM052bmZ2cDBSTlVvbnhkMjgKEIcUVtJg0HHHA1M/A69qIAbr4F/89MUa
            LjBbLoE/txhnWxyO7213M9oGkKmw7ZGTPLz6qOt0PT1lY/E+1DL7Gg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-02T01:03:04Z"
    mac: ENC[AES256_GCM,data:ET7sxFDFu4X2f3ek1ob7guUfO+adwW4wwn8JxNZD6Sk4glpgZZ59MibZKgpw1d3mb4HdoHu4G0eSd3ezI24WisRtVd57vSfAjDf6JVsfuabpobXCrxnmxXR2G9k2yyIjmusLQPlCo6zQNPlGwp+a6AhMq84ej7OCVoRqh2UXH70=,iv:XWcmXDYl3j/azTmWbVLJGL8m1KMprkxOxJ6EJLZSKlE=,tag:2lfBdTbEobpreryL9qkZLA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
