#ENC[AES256_GCM,data:K69+2OGWzatudKO6pN3Hw0uQgUcMEDWZIiUGzmuQTZNYcsdf+9DAFplHKLODG61sBBhlblyQsAWWA8/Zitrsrk/DYluhQ4qbXKO0LpwA8C58N3qayWYA4Fr6vP2C,iv:04RCuYL7YGcixPp8FLx6yaU6r0i3g6rtTfC35g3DNUg=,tag:eDW05oAPVNm4Jpxm+QZLRw==,type:comment]
#ENC[AES256_GCM,data:RmXXQyOkWz6znrsJgwdrT4SlIbPpIWYbdChuvX7p+GfSDcnZvzic249Gk4LO9eMdjwk4OwxK8Qg9MwUuAO4OgD7VHAyK40CQL7dlnHa7ghiZ/RT2l081zwanhg==,iv:pa+pIxU4j/i0aWVXrtXQM3fym8hCEebsjITLIQzy/gc=,tag:rjuaYscbF6g+isjbenu6GQ==,type:comment]
#ENC[AES256_GCM,data:V5sEAJYxeDIEwqnYnLNwSCoju4tVWlN8QBFNX6CEuh7dZfHJsVSeY9P/KKNoNT3+sh7CiguOfYmlqFK/amlK39Yfu6MgiYOeTQ8t25OSdGauhA==,iv:6q+/jWvferhKu1u/S4KdlUov6FCJwTLB1SsudduTubI=,tag:OFmczCK0qb4HpIMJYgGrkQ==,type:comment]
#ENC[AES256_GCM,data:jJmD6VqdbULiZBbnfgtP2yU7kCU3GdmG+xRbVvesYPOsuC9C6hZFaB+YWa79jyEpfG0=,iv:qTzIQcNpHTqhWvW4AjT2BHX3DrX19DtOLYllcBPFz6A=,tag:8CGjklHrT9AO4nuW45CH0A==,type:comment]
#
#ENC[AES256_GCM,data:MPAN+ev9YOXVi1M=,iv:Itp4QtRVMvO192x4uKymE+Bzu49TeOEtpdgrcVJqzd4=,tag:bWopYynpaxCE5hv1O/iNAQ==,type:comment]
#ENC[AES256_GCM,data:ULNINjgZzRpXVU3iIZpix/cMkrLB8jNU50gAtLT9hvaKNTKlS0/6qjdXzc3jT4f+Wm9WkMA1J+HdclCnTr3NmVNp9jQ5IOog+jmSx9fDnX/a,iv:W3Xa4BsUbjjEF8ySkiWnyeGdgtFl9WUlZ5Dbx5y2ZLY=,tag:+nqlLVGwYI0w8Ry6KR/UFg==,type:comment]
#ENC[AES256_GCM,data:px/QRRQG8+pTZ8P+Q6A2zvVPkZHn6oLN4+qHBT1T7JRlHNuBCPPhqo+QNbwRSsY=,iv:Or3pAwjFtOrv3CMuPSWdiyYRz1trqU+QlSS8JBbWY+0=,tag:oeHwDTFIiaDWlyugRgfZpQ==,type:comment]
#ENC[AES256_GCM,data:aBHy+zyv/6TYt3fIcNzd1eeksqCYjANjhkVkAMaKZ8LaHhc+0OBDci0LLjVsqhxYJmk5R+aJN0OXMs/PQt28JFcg2OVaTM6KIW6BqzTrVUr3j/q7hXhl0w1t4Fvm3YsXvzxt2cespkGtT2qe79MV,iv:9yHCwNfyJm9VajpNkxjq77FNC2i2XnNwOiFMfbnPy7o=,tag:9xdQeKT6gk2NHfJqzmarNA==,type:comment]
apiVersion: ENC[AES256_GCM,data:13Y=,iv:FFf5m2TCGuARnjde83iZw8wN/ueFcYZ+pf88oonAG5o=,tag:avjJ9P83aacLyRnLS9C7Iw==,type:str]
kind: ENC[AES256_GCM,data:Z5a9xY/v,iv:CAj2RnBaccbWwO7dwQokdLDl0GkdLz0/88uG1I5QOi8=,tag:Cqien7aBPJfjfy6MlSCYMg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:z801LBe8FGaNm00zJEyDBCR/Qq03X2w=,iv:YUuJbGUJiBCjTv/DfYUmVQeOD0BA2y8II2IvBO7UqP0=,tag:q7nShqclGHtpzufOvJTo4A==,type:str]
    namespace: ENC[AES256_GCM,data:3WmQTlfR8pt3Nxs=,iv:kvVQ9aYLGmCJwfXcCDWCWpT39o4oa9P+aiynmjF33Us=,tag:lM0FCeSInNjMlLCKzb13/Q==,type:str]
type: ENC[AES256_GCM,data:1nOxm/ls,iv:YgeFKDXfPCmi0iVoYmxIHRvN6ZJmIyJQDQi+ieD+Ju4=,tag:PzZfeHUde+amSrk5Ib5YDg==,type:str]
stringData:
    username: ENC[AES256_GCM,data:Gu7r8g==,iv:xJWi88TioVnzMAuL3nbct//yAfzQ58xsbqDwKDMDt/o=,tag:CjHYMuEWg8SqUkknCoEwKA==,type:str]
    password: ENC[AES256_GCM,data:p/74/WTcgJIR8Ke4cw==,iv:cBdqddrhf/Q1XoocWFOEXLT003y9a/8c2TvDCz9lChI=,tag:+ZtWC1RUdpC/Zues49C03w==,type:str]
sops:
    age:
        - recipient: age1qntcdwtxrfu92lhj2nzhlc3uqt8nxks5vw7rd23w2cj7c0qyuqqqmey085
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBReFdsRmxmdCtTdkpFL1Va
            Vm1idHNpcGRDUkpMcFlkdmsvN09Ib3NQVkZZCm1HVTRFZ0Roa1ROUlFReWhodThU
            TFVjekJCcm0zYjFvSURDVjJ4MVVzL1UKLS0tIHp6VUxXbzROaVJvL3lJNGJDL1Vt
            VlFHcjBoaGxZOEM5RlJxZjhkTXhrWUEKzLBaKn7PdQ2RuNbBL1uykuFOB2tkal2o
            8yb8KvRzMBZj6evDLbXCD2dKW453EtD6ntA6qt+7FAufW45rh+/HkQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-24T06:04:46Z"
    mac: ENC[AES256_GCM,data:mR4DiLVMsgfcptSKJyI8W1H23RjPjfHd5QAcg4l3cgO1PC4fskRzpcSaeCLH7rbxU/lbhQUM9WozmFIoh06LyujxfVLudP9Zew6Q5aTBkz606zoT7+0NErEa15UzVhf74exh/MxkHmxwLJIAbHdBtn8IT1UPYYo4QE7gXWtl2gQ=,iv:MJG57eTVgo2mhpntElSqhmHQTIEfwo35CuZivFsgWXQ=,tag:H0L9fNhNsbWNUpt02h5f6w==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
