version: "3.8"

services:
  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    hostname: grafana
    ports:
      - 3000:3000
    environment:
      - TZ=America/New_York
    user: 1027:100
    volumes:
      - /volume1/docker/homelab/grafana/datasources:/etc/grafana/provisioning/datasources
      - /volume1/data/grafana:/var/lib/grafana
    network_mode: homelab_bridge_network
    restart: unless-stopped
