---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helmrepository.yaml
  - helmrelease.yaml
  - pihole-admin-password.sops.yaml
  - helmrelease-external-dns-k3s.yaml
  - pihole-k3s-password.sops.yaml
