apiVersion: v1
kind: Secret
metadata:
    name: pihole-k3s-password
    namespace: external-dns
stringData:
    password: ENC[AES256_GCM,data:gXSbf5ltYbeYeUEiPQ==,iv:ffjtCJMETW8l3TZa3ZefHaq5iWVv82LJDywXOnHA82Y=,tag:uklLZ2nLGon6tooG+Cil7w==,type:str]
sops:
    age:
        - recipient: age1qntcdwtxrfu92lhj2nzhlc3uqt8nxks5vw7rd23w2cj7c0qyuqqqmey085
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3OWlINU5DUDJoQitzRlFq
            N2RoR3FRc2gvMFRnb09tUUlpemhleE11ZjNBCkFLQ2MrWENIeHVKTXpnRGlJZVZv
            QlJjR3V3MmUzR0VGSDA4am9Nc2lvYlkKLS0tIDZEc3ptTWI2eVNRWVl4WXcwNHRV
            MHBFbUw0Z0oxVUdHMjZETm9tVSsrUzAKJ4xgWVau3qKNRCSj+i8nQ0aIbHLojJLq
            4CQRVEBZCSfmpM5xSoXRi3LLo7WhmACMhAub+FZCYuipYxNZ3WKk6A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-02T01:03:04Z"
    mac: ENC[AES256_GCM,data:RNcBjTyiWItCpQH/CHZ/M/qVe2LjJNFC+nGCYGpyHu8Ymg/oVsvRgazAoCS1/eXoKiaq+1pCQQvdjXxd2yzyOp85cQO/BeGQgn2AAI2gO/Y3lTu6ACTs5Vsco0wrK4Wu5ZEgokcVKbODznXrsYKlOcu4zR5QyrEDg+tcuDve4jM=,iv:xBuCiz+e2ji+DWJXxWkdd5DehUtN9H+hpV0aZKNGtHk=,tag:GNq10HORXGzkYMQv5kZ7Yw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
