---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: portainer-agent
  namespace: portainer
spec:
  selector:
    matchLabels:
      app: portainer-agent
  template:
    metadata:
      labels:
        app: portainer-agent
    spec:
      serviceAccountName: portainer-sa-clusteradmin
      containers:
      - name: portainer-agent
        image: portainer/agent:2.39.2
        imagePullPolicy: Always
        env:
        - name: LOG_LEVEL
          value: INFO
        - name: AGENT_CLUSTER_ADDR
          value: "portainer-agent-headless"
        - name: KUBERNETES_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: AGENT_SECRET
          valueFrom:
            secretKeyRef:
              name: portainer-agent-secret
              key: AGENT_SECRET
        ports:
        - containerPort: 9001
          protocol: TCP
