apiVersion: ENC[AES256_GCM,data:tLs=,iv:ZxCkEmf4QL8cRk4nWHhIQtRN/ExHXUkkzlCB/K0xEmI=,tag:SzKolEPpuClhZpYwWf3hMg==,type:str]
kind: ENC[AES256_GCM,data:ZZYhFpTM,iv:9kCebTW6iPLyGi7a5EOoRM1sk+YZvTCn+IPgGnHdlYY=,tag:c+s1jCbOU3QByWLrpqVB2w==,type:str]
metadata:
    name: ENC[AES256_GCM,data:uUX/fvXT85hMCuSL6adNOg6meuJQvA==,iv:c2M6XSYxPQ74+3P00XmcYE5ZRaCW1uH9DCHpzOOFvMA=,tag:LGgeYh8uF2ePo4VAHuo9WQ==,type:str]
    namespace: ENC[AES256_GCM,data:KRGsbA6oP7aH,iv:siMw2Qe27CUrpeLHmnJvim+JmnqxFEXNKgmR9eAuJ/c=,tag:8upaVuA2l29ko/xfU+bDZw==,type:str]
stringData:
    AGENT_SECRET: ENC[AES256_GCM,data:5jisnI8tx4MXk96Wth5KQd7aCcsUGN2kUG5q2dSdX9u+ZqJEDuORZ5cRCW+0S6ktDNRozBgp/duBxkOfRjiLTM2giApVrgzbxsaYpWUy3nPr/cns/7lz6St3N1zkj2v7YXYBq6VAUVpr+8H6t3PM6/8JAshjvtI=,iv:Td8E7FQt97Us5qc8oNF/LNH7t94JedHL/E6oXvfnq8M=,tag:GLx2Hn8v2nfrhS9QhVsS5Q==,type:str]
sops:
    age:
        - recipient: age1qntcdwtxrfu92lhj2nzhlc3uqt8nxks5vw7rd23w2cj7c0qyuqqqmey085
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtM29FN3ArTkluL1hmY0lm
            bllRNXVXUDFtWUJuKzZnS08xOFkvNmZTdVJnCm1SVW5GM2NOQ0V2eEV5REphcFdO
            d251dmNZRHA5QjhHZ3VQY0xLWEF0bzAKLS0tIHNScURNcnVTczcveDdLanN4UzF0
            NXN1Z2I3bG91TEpSY0xwRUMxMVd0WFEKhMkz5bGsPP48YQstE7JFnwGYbal33zrL
            2FhS/OOUTTvBV4AH0L40+UPwGoelUyWeLA+s25paalbs+SwgQ12V3w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-17T23:02:18Z"
    mac: ENC[AES256_GCM,data:3ls6KWRA/HohWx+XnsMY1DXCn3fpDW3drV+mJDTSgU+rOT0rfe7d0J66mqW/JL4bXmg6bAX60W0gMObQxLiuuVDAZO/j3D3152jIUfnK7c9b8xJBs+0G/7UfLELr8mF+yoicPl1axKT41v7cV/BLIw05ufeidL1Vc3KoVY77loo=,iv:inTnl3iQfEcce+FdFSYuLOEfrspOPtQ9wK08vcRExM4=,tag:S61fCAKVZ/0LpSGT8/riXQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
