---
apiVersion: v1
kind: Service
metadata:
  name: portainer-agent
  namespace: portainer
  annotations:
    metallb.io/loadBalancerIPs: "192.168.1.202"
spec:
  type: LoadBalancer
  selector:
    app: portainer-agent
  ports:
    - name: http
      protocol: TCP
      port: 9001
      targetPort: 9001
---
apiVersion: v1
kind: Service
metadata:
  name: portainer-agent-headless
  namespace: portainer
spec:
  clusterIP: None
  selector:
    app: portainer-agent
