apiVersion: v1
kind: Secret
metadata:
    name: kopiur-nas-secret
    namespace: kopiur-system
type: Opaque
stringData:
    KOPIA_PASSWORD: ENC[AES256_GCM,data:BZs/T7Zu5thVHZRShmEiKnDAysrGoWUUKNOWkQa0omoIvIzhsqKc30ZnAy0=,iv:Cu5b6vxx9baPvuJXRglpMGyw6Ak/JjrkJI82Uv4bU8I=,tag:573adkiSORcGINm6Wu00RQ==,type:str]
sops:
    age:
        - recipient: age1qntcdwtxrfu92lhj2nzhlc3uqt8nxks5vw7rd23w2cj7c0qyuqqqmey085
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKMmJRRWQ0NjVKNHNwSlkx
            NjRsY3BkYUhNWko1eDU5cnI1Sjd5MXRGSEM0ClIwc3R4Q0dKMU1ZRDd3TkNMV0FC
            SlpzWE9pbmVqTEVMSWdlTkk0aVNWSUEKLS0tIHpmRHBkYXpZL0FKRFF0Y0lGQi84
            UjV3UUNyVWE2eXdhSkp3ZWpRUTB6QzAKuFqcal8YjAeSpSgNrWWiMQsCKMFIXbuE
            i4KHPKYh+uC53fbS+ICr16JoP0r6sLT+jAe2J7Ykv5GccMrb2mnfow==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-09T21:57:18Z"
    mac: ENC[AES256_GCM,data:Cj0o1p3GZ/+Qf757zebcZezxWl4vKW9IGQwMTDXYxiW7a+1M7RCuafp8dfFhUQaTwU6/DZwCXFjIGxnXYSLYUWqGl9JNpq3NuzVdifP7MH0xbdaMydcUjsUWG3wG4g2S7KmQA1nZTKXUAPjGpy3bjnLBwCKlDEcQEyMZz86cWZs=,iv:PkIS5RuBRgzpIaY3Z/jHMzdXvYFRNQi4WJFAvnBVg5c=,tag:XgKUvFdQYvTBQFCPVwyIXw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
