apiVersion: v1
kind: Secret
metadata:
    name: authentik-secret
    namespace: authentik
stringData:
    AUTHENTIK_BOOTSTRAP_PASSWORD: ENC[AES256_GCM,data:+2zNR9thdGqzlXNlMP4sze1RxtUet9yp,iv:oYUrSbg2eM64HuphDraflZc8Zqa6YKIXW5odtRevtD4=,tag:Cqjup4lmNbTkavFYuYFmpg==,type:str]
    AUTHENTIK_BOOTSTRAP_TOKEN: ENC[AES256_GCM,data:CeJ8+UK4bM79WCkMfez/sDK9gnr1OT9B+RPN+l7jYVaInOgwU/eMOA==,iv:WBPRd7mkD+sWKG5FTxP0fdCeiTGs4ZpRzow5fk/J/Cg=,tag:c2gH36Y8rJfmLbNFRDYUPw==,type:str]
    AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:IrpDGTHpRl7yX6gxw5oaKfcRx53NOkeaTJHpZs1pjMGFPl1x0+V2PYcV9vUtHYmhqts=,iv:VRinO8nTIFSLke4MLgV1flpasnxd9mpb3zfEnJ5dr/E=,tag:AM3PCmHXt2xQ1q7Cpv0K6A==,type:str]
    grafana-oidc-client-secret: ENC[AES256_GCM,data:pKCLAom7CZfSCC2TNZYsL+K9IyDm+EQfIL4f8t5W6j8=,iv:PUV9G6TuBaoNWjqJSv/lPPSvYFOMwKst34GfjwKmUOA=,tag:s9SgVWrh8WzK6T0uBQNMMw==,type:str]
    headlamp-oidc-client-secret: ENC[AES256_GCM,data:7g4wFCQH2yWzT86SvcmKYsbsMkWV1wFWAsspbLQkMRA=,iv:sUkFVHYDCz2Ydn0hqoQ8Gp0VVPgrPpA5h6pu1ek1IgA=,tag:kYEUpJyG3b5q/jIyls06VA==,type:str]
    outpost-token: ENC[AES256_GCM,data:JtTHAkgrSvrCKR6ZeouNUJqVWlyqMzwYpTbJlW4f/DUQMKt+YT49Uj3EdCsVcfYeTb25AcfRBz578VwJ,iv:M6zLcpPbcLckcWjqej4x605HEnaQAsoScTDAQ391fHM=,tag:0kDx2fy9Xc4VE+A3eY9scQ==,type:str]
    portainer-oidc-client-secret: ENC[AES256_GCM,data:jN3po/eCYxKrnF7FN2/fIZ7NUs6nAoOOAW7HC+/PYv2cCkVyPpzPstuFVFt4PedD/QAYs062Rx6LuJMC521WbA==,iv:dtcr+qXU5wp8dWEpsUcPALahOYPAphohHE/CCHS1Sw8=,tag:cBGVJrnCPvxoulG8iuBdRA==,type:str]
    gatus-oidc-client-secret: ENC[AES256_GCM,data:l0GD1+u2ZZsp9W+4d6XSri4xwtCQiyNh9OTU8pOdid1et7twc1grZVhxT4sJAjeIz5fjB/rO/fZEjlz3oSiW,iv:eMBliiIIO6K0gt8oKmPE6gC2SNMjMHbME8HmnpYi1rA=,tag:Oe07KPGWOh3YSISXat3RDg==,type:str]
    postgresql-password: ENC[AES256_GCM,data:IPNLtvh0FnV/YdsCVMVLE/N43jsLCZ0kmxpP3uK+DNY=,iv:8hIf62jJNLJalt4naTFqoIh4Ajm0a65FJZgSW/6BZkU=,tag:W4/JPUsKplqOYzJV1YiD1Q==,type:str]
    redis-password: ENC[AES256_GCM,data:zDimQ6Y9qj1tY7BUQZuH3lB+72kEq/SJTPXgGsBwm9w=,iv:9CjZ0y9UjH+ZRWFcjmKeCGjUJoDGVrvjkH25Ee5Bxj0=,tag:UfuMDXlePZXnWD6m416BeQ==,type:str]
sops:
    age:
        - recipient: age1qntcdwtxrfu92lhj2nzhlc3uqt8nxks5vw7rd23w2cj7c0qyuqqqmey085
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPVi85Zm5IU1Y1NkxJL3hE
            NVBYaklGa2gxamRXb21KYkx5K3pmNmVGMWlVCklpY3FWQjcrMGdyaEQ1aklzVldO
            d0ZwMUkxSDBsOUJsYnJxRk1sRWowa3MKLS0tIDhwL2tMUVlmaVM1TzdQV1YycmZ5
            QmRHNlA5ZisvQVZic1BuZEd3ejZWRmMKcI/udsiu17DuluFvvxF/xtKLxjLJIHOV
            WzAghp7ZyU9YvKhoGExBndGoDiuJM35jjLY7XQAACENxWihagIa8Ug==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-07T01:33:59Z"
    mac: ENC[AES256_GCM,data:i+k2CI7VHWJeNfEDzaYwBOhTyEx1ZzxlC3abMz+e+GTqI5OqVFbSxRBs9t4xVsDExD+Tl73nlLtYITxKHWxmV86vGgafN3ngUWQpRWN01sl275JsJ5eZ8NqEom8ZjNgcETC7IKdrCBPE/Zi7JsPyyseBY6r6ALSKcpX1Mq1ZyU8=,iv:Vj3zo0Rjo0NObqdUGEVMR6As1fCq9CW6USyYF6SKYDE=,tag:guNFDQekud1VvpeFxHaukg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
