apiVersion: v1
kind: Secret
metadata:
    name: authentik-secret
    namespace: authentik
stringData:
    AUTHENTIK_BOOTSTRAP_PASSWORD: ENC[AES256_GCM,data:BLDY/8DpCnc+TeuE7uyJrA+zvZD5tcm4,iv:l4HHCyHvVqCExVawBNZ0DcMYsd5oqVaZiAMToN8E98s=,tag:8Ih4VotQDYtsiNnmNLrMjQ==,type:str]
    AUTHENTIK_BOOTSTRAP_TOKEN: ENC[AES256_GCM,data:l8RQTq++k5S9sXu1Q19E1idjhzLx2NHKc+SI+/f9AY4Y/bVXnxEyrA==,iv:eBwkEkOT9mBOQ6435by4Yw7Gt+GDY4xyh9w/1oU4K4M=,tag:tYZxD6AryOF9IlYz2MjfAQ==,type:str]
    AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:GXC1KQJe79Ljg25npin6DRU04ykqPt4O6Twzp/5hz1SYxU6wGhHUTED3RQOdFOvbyW8=,iv:0sLQ7JWqG7n686csPmH20Fnda2F/hRfFHUbQgEc3u78=,tag:HqFngn6vTtHCcW1dYNggPA==,type:str]
    grafana-oidc-client-secret: ENC[AES256_GCM,data:i1esVa941j616BZZaxFp5ha6BM3F0PO5fzTfSM0hv6Y=,iv:1kRPZszXsKfNuKLdTcDX6SPUj+FejtC8+2SSdgwvRxM=,tag:yqFD8o6vV6f8Sf33W4f3Bw==,type:str]
    headlamp-oidc-client-secret: ENC[AES256_GCM,data:X7Jl3miFqUeGVaTKDAz7tlDtcUeRntNP1rPfXkjO+is=,iv:RMll2EUebnhHxOr9nw6lSmmxciqNzx5x9xfu8VUMmFE=,tag:Em3EqdDQAh/CTCpz8TclNQ==,type:str]
    outpost-token: ENC[AES256_GCM,data:oPiB1nnYgKoIzHhtpTVA8Oj/2UDVmWg7U8jQ/zy0NQp5N8wHcgcIgQNn0t5mIpBfvB3gFKRdSOHlQPPK,iv:6PZDB9paHFKcbyHnfklJYmYDOctRPDNtReSE6+87rFk=,tag:XqzgEuB9GfiFsPwWIDxtwA==,type:str]
    portainer-oidc-client-secret: ENC[AES256_GCM,data:bHMDWneq1NS0aXa8YXPMCAcEWT78RYpHiRWmfPRDNBhsPjmVfahqF7Uc/RNFn19dtBtYLKcuNTu42pBIbYHlgA==,iv:77yLmgEneht7bG11DtFpNygNi9tkS0b5TeRX8X3ku2A=,tag:6wsUbEUaz/L/B98QiJ87dA==,type:str]
    postgresql-password: ENC[AES256_GCM,data:kllmtrVMNJBK+XGFRuSj9LBMeJrgIvZnnppJb9qhqTU=,iv:V+EWPfo+67Wh/eawpoH1vUuml4RPfYohH7NDiUd5x5g=,tag:4+k+cZoljU+b0rD6CgI69g==,type:str]
    redis-password: ENC[AES256_GCM,data:T708POBgIGyGcT+3NnyCSLcvSnvl4ue70oiNiQKAhPc=,iv:i7TDTP+JtXgPJNER6NVl1ZoyT2uYRPzIJRwrJMZaIb8=,tag:WHTt4jcEl70MZprv3HbVyQ==,type:str]
sops:
    age:
        - recipient: age1qntcdwtxrfu92lhj2nzhlc3uqt8nxks5vw7rd23w2cj7c0qyuqqqmey085
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFWnViQm1aNlNMd2oxVUhT
            T0NLeCtjaVNyMURhb3BNMzhpSEJ6S1pzRFdvCkxWZ3E0aWhZVFdNbUhqZmFZWEJ6
            WDArVXdGL2t6cTRrOUhzK2dZR2lRZDAKLS0tIGlXdUwzNSswd1dvenVXYXZFckdM
            aEVRdlE2UW1UVUlaRWNFZ1prZ012cnMKloCavY0cfPMbxAY1bS2rvJUZM18IFmT9
            AxopG7sFUeRJhOW4abVqiD6Y8wIBITmBT1V8KIniy9C6SflksreJ/g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-02T01:03:04Z"
    mac: ENC[AES256_GCM,data:lROl6X9nq7LBMQeRobvcNeb5Nsux7m8+MlhE2W42wr0PmjQkXa2gdNicbfmylgIqYDvd4TmaVZUtTUaLgdh/Mw6Bc0x6cOdmkAmMKoz7bnwAKLkQGF9mI8ijmMFRZcS9ekrvBY+6Jzu2r/35hSH4b70PyDxjbbGuvo1Gh5GsnZM=,iv:joIngVf7kpelNbwjHJrc24H0SfGiUABn5mHeiyxXdaE=,tag:qotW+J3SvtGDxvcgOqCmKQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
