apiVersion: ENC[AES256_GCM,data:04k=,iv:dsda42iHnzuRNNfErbyAf93k5hoD7dm/BNgbeW/uPM4=,tag:0743OlJac8gu2BwzSCkCEg==,type:str]
kind: ENC[AES256_GCM,data:IkD8paqO,iv:JjhVEtEZGt6Ijae8UVfqtDN4NDWArqvIIuy0H8UUEgw=,tag:WgwVC29FpVyGUcYGaebWZQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:B+/+WZ/ddLx04AtHkxZEQQ==,iv:pEu4AM7MJ/X8e4PHdf+4ZIGWNpWG2AjIhJHSciOPEC0=,tag:cjDzUPBaJpGZW3N0gQfogg==,type:str]
    namespace: ENC[AES256_GCM,data:WfW39iK/yKe8,iv:YxU39w1SZcnqfd15bIi5fS9ANQNkvqxq9/B+CjtI/uA=,tag:Mcfhyh++B3AWJh9mDewjpA==,type:str]
stringData:
    AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:dGqibun2KEyaBCai7Xpm5tHuMi2TwBjO/U8baUsYN1cnK+K2iVxe4rSWaoSzIeBWhkY=,iv:wz+I4s6UxdbSmqa2zAlMizLv0UWK/5qUrCzcs1+ga9A=,tag:CWg5cClZSzUAYo5NrJUhWg==,type:str]
    AUTHENTIK_BOOTSTRAP_PASSWORD: ENC[AES256_GCM,data:b//FwhM49n1jA6OYbUqq+D6ETRUBwj3d,iv:QAjluTRx8ESmC0NeMQ3eyNTcENKgPVUgqzkx/F/XaHo=,tag:7jKOF6HZQKfTSEdnMK2BWg==,type:str]
    AUTHENTIK_BOOTSTRAP_TOKEN: ENC[AES256_GCM,data:F3WRrOY5grSIweYqNHCjGvmFauwzRAlC+6M0pH5teqg2PERDi9jfJg==,iv:JJq0N8HkU1Vef1IB9XSWlzMzboy28t7fOmVf7gaEfhY=,tag:U0y+MYplYMIDSA11jUXxww==,type:str]
    postgresql-password: ENC[AES256_GCM,data:36daa5SThqqR9/oQv/8RInIubZlG6bLlsROosG8YA9s=,iv:ivZaNvmlcC0qSxVei70p/qN3dXN2TVG0pbd14iBu38M=,tag:J57ZxGEr+5EbniyoVlw6iQ==,type:str]
    redis-password: ENC[AES256_GCM,data:AqYpLtlt49idecW+mkES02Jp+U76kE9KJpolhbMTXPM=,iv:QNB7qq9eNO7jaWL0CdhxF0BDmRAlgrkdO+bPC0/5DHQ=,tag:ZLIFFtzpiuz/ZXi8kYFXlg==,type:str]
    grafana-oidc-client-secret: ENC[AES256_GCM,data:PCFMGlwPqWsTE2aHkL7mgdZVDSyRUc5Hnq9rW69pxm0=,iv:+ASCWnqRv455q3eXH/TNo6eJM1jnREcfCWbr/G7c0xQ=,tag:/GPFoxUa29Hd6/fxRs4oUg==,type:str]
    headlamp-oidc-client-secret: ENC[AES256_GCM,data:TSu5wOQLWZT9pjDwkjKpiuM+CfN93vYNDsNV0kff++E=,iv:3hshuJuu2SVPbqZvhEscwKUp7Vju1tuOLATmYjOSw3E=,tag:PfLyr6BnNVAxaogX6vZ4Ig==,type:str]
    outpost-token: ENC[AES256_GCM,data:mHuEzJBrrWn8O1D0VMHaDbFIbaj1HbCN+pu4zIEWHml27JrJ7ul+EQ==,iv:Vv7x+1JG1PAmnhtkFeEfylOJbqzBJ22PxM/oIg2lx8Q=,tag:pWqLeXjFx9/3UOzEVA9tXA==,type:str]
sops:
    age:
        - recipient: age1qntcdwtxrfu92lhj2nzhlc3uqt8nxks5vw7rd23w2cj7c0qyuqqqmey085
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRN2tjT3NPUHVkNTRnTDZP
            NFllczVYU0dXQ3llYWpkRlJWQ0YwNnVmem5ZCm4zeVJCM0dNcnVMMFNnMDJZN0lt
            LzhQdlQ4TlRhVFBqTTFnaUxEWVl6TFEKLS0tIDUzbXJKMWVrUlhjUUxqemllTkJS
            WERVdk1rMkdEa1dsWHFVa3d2eWNDZzgKwCd9g72JY5/22KzAaB3JBCd2OW0Rcp+7
            D7JJnuTBmI0dde9ZVa83AH1JqZQD6+2pRX0e0lnY08uU7QFULBKojQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-09T19:26:55Z"
    mac: ENC[AES256_GCM,data:Hatf4xYRGyKiVakfwL442ISitr79P4qMpbwSo7UtPNZkslioN/Tdg+YKt4OSwUSDAHD9jcthRlU7zXxzkFkrYDY3VNqIMZmztaFbsdLbr+0dC5Di0mDIa5KLZebBx2jAgc5F8ahB5cK50sZDKGeKiLa7snr9S23V8Ml7K+XzQsg=,iv:GzVGJVqCwi0TbC6XFIX+FEMJ0hDUAFGpFOEOQRAEqwY=,tag:As1fY4bH7EG+X2xnmgZrag==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
