---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helmrepository.yaml
  - helmrelease.yaml
  - authentik-secret.sops.yaml
  - outpost-deployment.yaml
  - blueprints-configmap.yaml
