version: "3.8"

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:2026.05.0
    environment:
      - TZ='America/New_York'
      - WEBPASSWORD=admin
      - ServerIP=192.168.1.2
      - DNS1=1.1.1.1
      - DNS2=1.0.0.1
    volumes:
      - '/volume1/docker/config/pihole/:/etc/pihole/'
      - '/volume1/docker/config/pihole/dnsmasq.d/:/etc/dnsmasq.d/'
    networks:
      default:
        ipv4_address: 192.168.1.2
      br:
        ipv4_address: 172.20.1.2
    restart: unless-stopped

  pihole-exporter:
    container_name: pihole-exporter
    image: ekofr/pihole-exporter:v1.2.0
    environment: 
      - TZ='America/New_York'
      - PIHOLE_HOSTNAME=172.20.1.2
      - PIHOLE_PASSWORD=admin
      - PORT=33302
    network_mode: homelab_bridge_network
    restart: unless-stopped
    depends_on:
      - pihole
networks:
  br:
    external: 
      name: homelab_bridge_network
  default:
    external: 
      name: homelab_physical_network
