apiVersion: v1
kind: Secret
metadata:
    name: prowlarr-apikey
    namespace: media
stringData:
    api-key: ENC[AES256_GCM,data:TsLisnycpsyDEOARrwd+797mvXtYPvLsKGirVOyDZXY=,iv:Y2b++iYjEevx4l8FrdON1qOQfvk9JAAyiBytkvy1dbQ=,tag:DpRTUo6Iho+Rz8jifMsLzg==,type:str]
sops:
    age:
        - recipient: age1qntcdwtxrfu92lhj2nzhlc3uqt8nxks5vw7rd23w2cj7c0qyuqqqmey085
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFVzE1NFhSTzZHMG5OYlRO
            eXNFelp1TStnOGZSbTlRQzJETk5ZMmc5WXdRCjFkb3pwVERMRDZaUDZpY3dqdGZ6
            TnpqekVudVF6MnRJQnpNWFNDaWFnSDAKLS0tIHFsQ2NNMnZoOVlEUFlwL3RyZ0lO
            K2ZmWXErcFp0aVNNeXhkUEZpQWh4WFEKTuaw0umcAFjQYZ95m8PgDrfIGTN+gHK3
            /EOB1Ccnx3Xeop/fb4ZJ3/B8S/eamdETMioxueXpbeJflni3OK6b5Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-02T01:03:04Z"
    mac: ENC[AES256_GCM,data:Oj4dkEhchNvrYHeU/Mr2IapH2/oOt+x5t7PJV1DNooFCoPwXZDubcwhYfIDduRSBdkHn5hjlIe1kq8SeGnfCcNZun46Luqz+EofvQLk97WbMSf6x3CJn4wXvQjxnnHu0ctZEZTh/4SKfzfVfWNwGKn2OEwQVw6y4M97grcgeStM=,iv:yY+G/3I/xEzZOVUAIhFb7NKJgNdF15R+JqP9i2C52GE=,tag:zo2fTOF6+Ek7TEGIotq8Sw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
