#ENC[AES256_GCM,data:Qj6g8MVzMTl9L7ZfP+9zuQysLoCiTkO1dbQIfZDPL3vloKNOkArDAUT6JsmgQRHFv0DwYSCyD0YGHrf7eVqiTQo=,iv:xrCP5Vd1bmAvVRIr0JWq6Zh4zFMHTHJsV7rWNRhDFVs=,tag:WFsIOkXDlfDs2kZRaRwy8w==,type:comment]
#ENC[AES256_GCM,data:Kczr7EuFwxOn4KAtFZ5Ms1EnSEVAqWG9b4macGwhZ1oTrjHUPn9Lx/jsCA+B9OVu0FOeaq2XB4712G5YaJBdr4k=,iv:wRB21qxM++u3qXaP6TXVvBQ3gHhlYq4wsvdxWmwMego=,tag:6BdjCLSuJQ9D/hOqo2y1LQ==,type:comment]
#ENC[AES256_GCM,data:GdWalx3oEVLrn+pHC/m2hhMpi7fKaZ/YsuTQI1E42NUDqQmjJH3wDYY=,iv:zfAwDnbp+GuJcvX46YTt55J2savXtoUPWDeK7bwxZSM=,tag:IimoMxneTishA/tXRM8Thg==,type:comment]
#ENC[AES256_GCM,data:xvTyG1AqiyzZO5cW+b2FduOB6HxjfVFvKJCZOC0/q2AmDmFKP42q8qnL,iv:XSNGvuqkU5H8Oo8xlwuO/UKFisU0qCvwzb2UhOwL6nU=,tag:2MW0lAJc2ml9YByTh8oViw==,type:comment]
#ENC[AES256_GCM,data:V+CTfKm2gjD9DRl1JxYiYoFr0wWYDxEM,iv:LFo/99HyD40BKPuLIgoRwEtCHS4fbo8KmYmG1poDSZw=,tag:ugyjsNUzhDcJrzB5DNO2Kg==,type:comment]
#ENC[AES256_GCM,data:Lc12HqW4AIplMSbeZGLoV6z1aGPUe1KODFgCaWDpGCgUr6OJIkM6tbVkMb+kOPJGLIjgj/xDC8+CezPCbxm9k7Jic8ZWJh2HSvmHSrZyrMgKbm4KHCYrtg==,iv:EUGw5DVUB/k1OZ2ys4fxF9O8t6Qvj81MoJIovRoaCmo=,tag:MmuivBRuMm8l5Fj/035JQQ==,type:comment]
#ENC[AES256_GCM,data:c8lI7wDRqp1kPuZjtsp/FwCNahxFrnk7v4c8w5IApi1O7eMrSJtlHShLSlRZE1x8KnkuwXNf1XzKkOFQw5RofttCQDRzklBW5FWooVTPR4dKj7u/mzdNz+JRymn9eg==,iv:NGAdLPgl/GXCN8hF0diY4hNkK13ut9TmgFUht5JJG38=,tag:GHrbdMZqg/ObRriaDj16nA==,type:comment]
#ENC[AES256_GCM,data:567TKWjcP5O9lgYDwEY3nOhUT25nuEKI8n+DA7duz+LCAmPuDnPrmDQZ0eKy4MxfMynxoVbHM47mAACKHojlkI4Vbdo83EUHLcjffmJ5xi/sxXIXnxwg0LbOPTft,iv:XSTW534QS/vxewIdhx4/+hHdEqo4Pu7n8xGDVOExN2E=,tag:1ibsn76KBlssC0NAQ7hGtg==,type:comment]
apiVersion: ENC[AES256_GCM,data:AQk=,iv:WY/nuA/3XYM6hYAW0PWVg/OMkPq5jkuR8nZXgzcQPjo=,tag:6mMe+c3O02Wc/0VGGPpl3w==,type:str]
kind: ENC[AES256_GCM,data:7ozRxe02,iv:ZXat06oiaNbvQq73JOkPSF5LzfBlvuFkWCwCniUdY9A=,tag:78A9apdPN5bIG69qIgminA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:JbcFWFyagGS2lnDbGwAPFts=,iv:wBhkMbMBr8sqbZfzHIswy3mIZuUFtb91ZZMIxIdtGuI=,tag:yYRbyKUxKsY+pf7Mdz263w==,type:str]
    namespace: ENC[AES256_GCM,data:7sUFIsc=,iv:umi4/VS+Y93N6y9nvuGNnWK4fbxs9cki8op6k91eY4w=,tag:9Udv5sUrY3vrpNBog3e75g==,type:str]
stringData:
    SONARR_API_KEY: ENC[AES256_GCM,data:RP9ha6/eDPgfGpI1nvWQXrVRitfURWtmoz4WTALcU8E=,iv:tpT4CASqtDspvZ0juaB7oHxvS/Hm3P3eOYf8b2/dm2A=,tag:E7/0zU6oKVwrkyAQls8ZaA==,type:str]
    RADARR_API_KEY: ENC[AES256_GCM,data:/fSbLUwYy+0cIJeWNottxaHZJVBrKOmXHJQzo09hC0w=,iv:9KBlnfXgZfHFhR0tlJ8MlWI/lfd8jWlbIE2WpkUr/tw=,tag:uuGmV+eN5+mEURssR/6XPQ==,type:str]
    SONARR_BASE_URL: ENC[AES256_GCM,data:2KdkSKAaoyzb80wcEnjkUQHXVseqfWY3pZ5A3j1z3TWF5JJ80WYYtSb/,iv:sNEBTTiopAMLct8qL7NDENKUPq0F2XqKO0DJ7GrdAzo=,tag:TGrhkfdRPrhscABZIFL8qQ==,type:str]
    RADARR_BASE_URL: ENC[AES256_GCM,data:IW2Ghp9zUBwmSYOywOtGfpI2VZvH23Au8IKYz6Sri1GFbrmEq3YaaiNZ,iv:WDuZPDnTCzysqmQOEOsfrsRWTLn7++qNwot2vO6Nj0o=,tag:j0xpuueY0kC9gMPbTTYY1Q==,type:str]
sops:
    age:
        - recipient: age1qntcdwtxrfu92lhj2nzhlc3uqt8nxks5vw7rd23w2cj7c0qyuqqqmey085
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5a0Z2UzJnUHQwMGNaNjB4
            ditWdkpNc2JqandjelJYelZ2OTNnenVVWHlBCmVneFdpdE04KzdHR1J3Z2VVdDV0
            MVFLVFRmVXQ1Wm5VT1M1YmlkVXIzU2cKLS0tIFpSSWIwOTFrZVpMNlM4Snc5R1Nt
            eE1oaFJVTnFZVHRIelc3ZUoxY1lYQ00K22qOYQuz8Ax1SPXX3uYeCjt1fYxWuIUb
            Q+pTQq5IKA6wp0NDesByIJyRrhB78wdFz/i6eK3RPgm3+9Us78kD/w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-23T18:33:45Z"
    mac: ENC[AES256_GCM,data:4eKNgAIBa6L491nrAZOfBzO+UZ+NB1G9FfcRK3zxxdtyT5/eOUmV7V9qi2NHI6G7EymMg039r1alxIc5PSRPiCn0DX1ed3TVZGT5hA1nZ16G4LZ7ejOWIbZvvbzouTujFyKF+rQ/xMtl1p3IOD1qKlZcEEYPMnuV81BBL0y6jUk=,iv:wbzlcjDbHn5mdeFJ/YMZDcKRUTYxL4ZKYSVh512ErYc=,tag:8zl1wnqQAhVx3ElEg+DklQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
