version: "3.8"

services:

  tdarr:
    image: haveagitgat/tdarr:2.73.01
    container_name: tdarr
    environment:
      - PUID=1027
      - PGID=100
      - TZ=America/New_York
      - inContainer=true
      - ffmpegVersion=7
      - serverIP=0.0.0.0
      - serverPort=8266
      - webUIPort=8265
      - internalNode=false
      - nodeName=synology-healthcheck
      - transcodecpuWorkers=0
      - transcodegpuWorkers=0
      - healthcheckcpuWorkers=0
      - healthcheckgpuWorkers=0
    volumes:
      - /volume1/data:/media
      - /volume1/docker/config/tdarr/configs:/app/configs
      - /volume1/docker/config/tdarr/server:/app/server
    ports:
      - 8265:8265
      - 8266:8266
    networks:
      br:
        ipv4_address: 172.20.0.19
    restart: unless-stopped

networks:
  br:
    external:
      name: homelab_bridge_network
