version: "3.8"

services: 
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    ports:
      - "8000:8000"
      - "9000:9000"
    environment:
      - TZ=America/New_York
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - '/volume1/docker/config/portainer/data:/data'
    restart: unless-stopped

