apiVersion: v1
kind: Secret
metadata:
    name: gatus-oidc-secret
    namespace: gatus
stringData:
    OIDC_CLIENT_ID: ENC[AES256_GCM,data:CPBG7ow=,iv:ZkNkEL2srYqLnmLv+xJtk31yzch1sLzgApoigr410ic=,tag:+0EbZAolrltQpFJrgFqm0A==,type:str]
    OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:jAvH1Eb2YH/QvPS1IaDm9VWoD+MVLBcnlq4y4AbqUJkzj0jIxViuXHCUJYf2nJDhuItYGuB7wgtWUiCOxiy2,iv:dPOD3qShzDCd6ApL/gSIjZ6G6HPEMf1qiW77Faqlaxg=,tag:LCbo1uutFsHrkGGf0bB7uQ==,type:str]
sops:
    age:
        - recipient: age1qntcdwtxrfu92lhj2nzhlc3uqt8nxks5vw7rd23w2cj7c0qyuqqqmey085
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpZTI1Ri8vOERKS1E2S1V3
            T2IvSFJoWG4xM0F1ZWl1RnBFRkl2YUlEcFNnCnY0cEwxcTdyRlhFSzRjVlYwaUsr
            L0Jkc0NVNmgwemp4K09HNnlZcUl3Wk0KLS0tIFF1T3REZlY4bzF0aWM5dFk4MERS
            MENiMS8vMldxYTcwdWpDempaLyt4aTAKfZaH3bOcVj7HaNnJ91YLFHzkzYwNhn1+
            C4yXx+Jxeu2XpyN8npFi3dIJo9UuS+NNx8RNbDmzA1Hc4yFR2K908g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-07T01:32:27Z"
    mac: ENC[AES256_GCM,data:0J9Ht8tLKeA6tvNWBinnzMgc4uHMVjpRBeIMoEy42qVOlY8cNYfjByBtsz0fbYwy3eQobXJRcKd4Xh91gmZL56hXqDI1ZD4rOMPvz+pneEKttUSTEmdKlQnCfsL3M4YVNmcURgbPIuZSxSdJbrxwzXA7W0fvyxbyLGyptzwY+eQ=,iv:UhT18mjpKGdZhqVqHiXl4yccRzSzpTJVVP0VXvch7Ic=,tag:tDvmghMHMcqOyz06sL63fw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
