version: "3.8"

services:
  transmission-openvpn:
    image: haugene/transmission-openvpn:4.3.2
    container_name: transmission
    hostname: transmission
    cap_add:
      - NET_ADMIN
    environment:
      - TZ=America/New_York
      - PUID=1027
      - PGID=100
      - OPENVPN_PROVIDER=NORDVPN
      - OPENVPN_USERNAME=${NORDVPN_USER}
      - OPENVPN_PASSWORD=${NORDVPN_PASS}
      - LOCAL_NETWORK=192.168.1.0/24,172.20.0.0/16
      - NORDVPN_COUNTRY=US
      - NORDVPN_CATEGORY=P2P
      - NORDVPN_PROTCOL=tcp
    volumes:
      - /volume1/data/torrents:/data
      - /volume1/docker/config/transmission:/config
    ports:
      - 9091:9091
    network_mode: homelab_bridge_network
    restart: unless-stopped

  # transmission-exporter:
  #   image: metalmatze/transmission-exporter
  #   container_name: transmission-exporter
  #   environment: 
  #     - TZ=America/New_York
  #     - TRANSMISSION_ADDR=http://transmission:9091
  #   links:
  #   - transmission-openvpn
  #   ports:
  #     - 19091:19091
  #   network_mode: homelab_bridge_network
  #   restart: unless-stopped
  #   depends_on:
  #     - transmission-openvpn
    
# Notes
# 
# 09/2023 - 
# - For version 4.1 the following directories are used
#   /volume1/data/torrents/ -> /data
#    But /volume1/data/torrents/torrents/completed/* is where finished torrents are saved. Why? 
# - Upgrading to Latest breaks in the following ways:
#
#
#
