version: "3.8"

services:
  transmission-openvpn:
    image: haugene/transmission-openvpn
    container_name: transmission
    cap_add:
      - NET_ADMIN
    environment:
      - TZ=America/New_York
      - PUID=1027
      - PGID=100
      - OPENVPN_PROVIDER=NORDVPN
      - OPENVPN_USERNAME=${NORDVPN_USER}
      - OPENVPN_PASSWORD=${NORDVPN_PASS}
      - LOCAL_NETWORK=192.168.1.0/24,172.20.0.0/16
      - NORDVPN_COUNTRY=US
      - NORDVPN_CATEGORY=P2P
    volumes:
      - /volume1/data/torrents:/data
    ports:
      - 9091:9091
    network_mode: homelab_bridge_network
    restart: unless-stopped

  transmission-exporter:
    image: metalmatze/transmission-exporter
    container_name: transmission-exporter
    environment: 
      - TZ=America/New_York
      - TRANSMISSION_ADDR: http://transmission-openvpn:9091
    links:
    - transmission-openvpn
    ports:
      - 19091:19091
    network_mode: homelab_bridge_network
    restart: unless-stopped
    depends_on:
      - transmission-openvpn
    