# Encrypted SOPS secret. To create from template:
#   cp cloudflare-token.sops.yaml.example cloudflare-token.sops.yaml
#   # edit stringData.api-token, then encrypt:
#   sops --encrypt --in-place cloudflare-token.sops.yaml
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token
    namespace: cert-manager
stringData:
    api-token: ENC[AES256_GCM,data:ZQYmUPnbrX9WsZPYZU8uebcAWAcyWvpJx/o24HqHur4NvryYVhHE6N3BRjJErWpVQqXIsiM=,iv:GiIzM8UFDIGw9PymrS8YLwZvl3Tr1eS2SWlXtmEV4L0=,tag:nHsw2nxqLeBdL/zboVwxRg==,type:str]
sops:
    age:
        - recipient: age1qntcdwtxrfu92lhj2nzhlc3uqt8nxks5vw7rd23w2cj7c0qyuqqqmey085
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0SXR4OGU4MmpDUHg5eXNT
            RFBlTlNydkRqRzZSUWFqRWhqWkZLWHlqM2c0CkFOLzdGV2pPWmM4bEM3Q1FJdnkr
            RUhjbzRvYnZhQ1JkQ0hHZCtuamExdW8KLS0tIHdPTnVDYS9maW9Na0lYUHVCYkly
            WG12K3R2aVRUMEowYmZxOFJ4dkdnSmcKYErp0pdEeR7vYP7XdS6c+TozBvg6BS70
            SUpFCDOGZJanE0pe7hrMQquFYarCzDQ24zJkTFqhnfTyhOOPhl8WaA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-02T01:03:04Z"
    mac: ENC[AES256_GCM,data:LLQBzgYTZ+W9b3wGhO/E4FXLZ+CE31FIGynb458ILm3cAjZahb6Ckeff7K5+sD+wLvq09dCyTn8qtajuX8f4rWbZFVG4IOQ4cdMHwq51jmNE++k/4diKl5SzAqJfW1DiOlwiqH1VRK8X3ITWEu+VRhRBj8ZV+7HGH8eG0Vy7XSk=,iv:FnMCAJ4X1jslXKdM2YdQdv0reCerF3OXW6M1u7XgePs=,tag:Dm95PCg7fkno3P9GKpRWlw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
