name: Renovate Config Validate

on:
  pull_request:
    paths:
      - "renovate.json"

permissions:
  contents: read

env:
  RENOVATE_VERSION: "40.5.0"
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Validate renovate.json
        run: npx --yes --package renovate@${{ env.RENOVATE_VERSION }} -- renovate-config-validator renovate.json
