# TEMPLATE: Copy this file to smb-credentials.sops.yaml
# Fill in username and password, then encrypt:
#   sops --age age1qntcdwtxrfu92lhj2nzhlc3uqt8nxks5vw7rd23w2cj7c0qyuqqqmey085 \
#     --encrypt --in-place smb-credentials.sops.yaml
apiVersion: v1
kind: Secret
metadata:
    name: smbcreds
    namespace: kube-system
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:4qPL9z6fdIk3,iv:+icOWjbZQf2yGS/eVK7cCbKz1ZpLV3VdD7xogUuu71Y=,tag:C3lAvXlfbb6K+IqyusDNCw==,type:str]
    password: ENC[AES256_GCM,data:kH/e8EpW32RyBE7F,iv:2ihJjHHsXgEJ+bmsOqz4JGE22IjJVUv/fbxS+CdtTGA=,tag:3Ao7vHTXt/xPPUOR8SnReA==,type:str]
sops:
    age:
        - recipient: age1qntcdwtxrfu92lhj2nzhlc3uqt8nxks5vw7rd23w2cj7c0qyuqqqmey085
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3clhSenI4b2VJYWFLdGFK
            Vk8zelA0QmZlRW9raCtSMnVDUTVnaVEwY3hrCmN5YVdnZ1ArdmxOT2VBbW1oQWJG
            dFVnSlY4MnkzN3lGQlN1anFQRVhXVTQKLS0tIEx2OTdpTGV1d09XOEtadnB3aGVx
            WExWS0s1OHpDdjQyam1ENlBjY2VWSEkKkQirPr06G7pADN6Z52o8gJOhdFnl4Mwt
            FDtVQCMAzIKpc6RLo+YKUWUNySbt8ixoTWcMXD3o3qVrRFFsZ6eKuA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-02T01:03:04Z"
    mac: ENC[AES256_GCM,data:/WTR3/6DJcwVHydac6FLy5o1C01DnXju3Zch/Z/6qa8yCbMgg2GZ2x2rEdmhC3BJsc3lu4362MTfQKVYesBkhJzMaCEkQSIUCDxHNQ3FEH3AtSMJeRWA2k4u7/R2/1wUSLutCx/OMzIJ/AhSQZcMn6d/r1Bb2GITuTdqxqURhRU=,iv:nUZN1DyzgetBapmsbG6iKZFT2Fyw3GEABFNbo9X3y8w=,tag:UQ1HNfKKcB51H6nbIlDsCQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
