#ENC[AES256_GCM,data:OfbA41pz6AO1THdyDvyWAKQ63dW1jewug0Mwr77UtxbGZTyZqv3k3va173T0YWK3k4NIHavK,iv:wzIGOHMD/8Qk/KQ5NH1pGbL2iY07PBP4LJQwcyyOXO8=,tag:hWRdjU0QpK9xnSPeIVt0NQ==,type:comment]
#ENC[AES256_GCM,data:SW5MJjrqhNV2CKvTKbAUVUGxOEoXRU3g2F4wm4eF+WoMctiPVZOruyfcrKrO,iv:wV++mdTtKagX1NQfJc+SIYFKfVnP73lRot5F2kZmvrg=,tag:Za40Eoe+gF7QJa9isphpBg==,type:comment]
#ENC[AES256_GCM,data:L5zkOS3FyfkTGAEP0JZizMTo5pGTMVoAuBksChyBfmetEgXUrqIrQBohq3bX06M63h49XvHbZ3j/7jyookvZ3x+2R+AHIpvE1NTh1B2w,iv:N5WQcbcvAwUVdqY7Rt/f7/jJJJlv8592IRJlAzpkZTk=,tag:BfDPioS0WFnFp73oH67j5Q==,type:comment]
#ENC[AES256_GCM,data:OMkrmQmwAYq2gqs5GdGCBDjoeVM3Ap2bZTjdKZ9xo+v0lPmUQ7du8YaCJFSw/cK/xSsE,iv:qbEf3JSIzYdJKcv+fCyItJyAcNWX37W7D51Uo0rqhN4=,tag:VzpafJ0S4GxWq1POj9pkGA==,type:comment]
apiVersion: ENC[AES256_GCM,data:K+A=,iv:2GG4NcSARVrGOhC973+HAmORu/2VnIhlqCuVA//0zXU=,tag:ApR95+VBkw4AYhKaprQJTg==,type:str]
kind: ENC[AES256_GCM,data:eRmk1VM4,iv:1IXPtU4auy1VptrD8wf1NCa+fgeWamMTIk41U2kdL94=,tag:nTugRA9g0HofOF0c8boLMQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:ivc3IDxIpfo=,iv:hJzI0cUMLuGM63GyEOEDr30bEQjCdV5Ny6QJQ6G9ybU=,tag:SBYzTE5MGGm5EWrCnlmNqQ==,type:str]
    namespace: ENC[AES256_GCM,data:kwlH36DV/Zjrck0=,iv:GHE4GBQKPL4EB6hGyukp859Zk96HJpgKUMk8HO/Hnh4=,tag:5Rs7k4JqbdhLZXBUCU5Uaw==,type:str]
type: ENC[AES256_GCM,data:rb0ZA5DR,iv:PXxzBnXKClD0VFB04d7sImn0Q73ZHaevl3KgH+sVUZ8=,tag:asAVCSz+qUUegMy8RWgr0A==,type:str]
stringData:
    username: ENC[AES256_GCM,data:PQiHoUTXeqxJ,iv:i0fmB5RdyYVHLsQEMIAPPLJobfeHz7SJCSeUZbesyVc=,tag:LjceIqnKOWSxJ+tVj2vwCw==,type:str]
    password: ENC[AES256_GCM,data:VCzGCaJhoCpUrLPp,iv:cbnVMa0ePVBDv8x4i5LeGA1Cr54gjmuJQRlG+s0VpIA=,tag:4VXjrKlsBFzvdfezu4910w==,type:str]
sops:
    age:
        - recipient: age1qntcdwtxrfu92lhj2nzhlc3uqt8nxks5vw7rd23w2cj7c0qyuqqqmey085
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiQWVvdkkrb2dhNE1xbjFr
            c3IvNGFlRW9CLy9obEpjT0NDWE9KYjRJdlFzCjdaN01mUm56VWJSTTZBUnZVNWRS
            U3dwOUpJOCtxbDVIN3JjR1BuQXp2azAKLS0tIFoyQVBMaGNQNDRURGZrVGpnZFJC
            dFFZeUlpSW8wMVNlYlp2empZV0tXak0KAoDOEuEbhCh4ve/t9r3/EaV37zg0Xeik
            LTlGNEC1RH6VWexYuNZe5vTKp7mwNEpCBwjFV2430YrDUM7moKA2hg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-17T16:20:07Z"
    mac: ENC[AES256_GCM,data:LgFzXXPw5qvAYP5IkGyOo7fyfz6Vmgf4NbnMUCFIZxOVaHWC6rqmclPv3SpMuAQ5QBbcSnH0+1LXmZ90ATt2TIKl6UOl4Pqs50eNeCM+oQSWaBXIcbheMgb48TiJywe1U88dtdopdzS2s0THtB8O3bgALCwtRdyTVmI8ZfM9l9k=,iv:hS1mBTHA1CDNb5miN0eOLByuHzWxjidZJwomLO5H4w8=,tag:+ZPxuh1UVjpifYXOnUJ4YA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
